### ISSUE TITLE
Can't add Toon Smart Meter and Toon Boiler Status at the same time

### ISSUE THREAD

**Issue by baba420** [cyberjunky/home-assistant-toon_smartmeter#10]
I successfully added your Toon Boiler Status integration. It can be added after a server restart in Lovelace. But as soon as I add the Toon Smart Meter component, the Toon Boiler Status component becomes unavailable. When I delete the Toon Smart Meter components from configuration.yaml, the Toon Boiler Status shows up again.

**Comment by m-Aiden** [comment]
Will try to help this user on his way through tweakers.. 

Kind regards, 

mAiden 
TSC-Member

**Comment by baba420** [comment]
I solved this issue by giving the sensor a different name for both the Smart meter and Boiler status.

[code=YAML]
sensor boiler:
  - platform: toon_boilerstatus
    host: XXX.XXX.XX.XXX
    port: XX
    scan_interval: 10
    resources:
      - boilersetpoint
      - boilerintemp
      - boilerouttemp
      - boilerpressure
      - boilermodulationlevel
      - roomtemp
      - roomtempsetpoint

sensor meter:
  - platform: toon_smartmeter
    host: XXX.XXX.XX.XXX
    port: XX
    scan_interval: 10
    resources:
      - gasused
      - gasusedcnt
      - elecusageflowpulse
      - elecusagecntpulse
      - elecusageflowlow
      - elecusagecntlow
      - elecusageflowhigh
      - elecusagecnthigh
      - elecprodflowlow
      - elecprodcntlow
      - elecprodflowhigh
      - elecprodcnthigh
      - elecsolar
      - elecsolarcnt
      - heat
[/code]
