### ISSUE TITLE
Qubino smart meter solar not reporting production

### ISSUE THREAD

**Issue by hosmancevic** [cyberjunky/home-assistant-toon_smartmeter#12]
Hi,

Recently i switched from a analog kWh meter to the Qubino smart meter for solar.
The Qubino is reporting to my Toon, as i can see my current production on there.
But since i switched to the Qubino Smart Meter the production is not being sent to Hassio anymore.
I can still see my power consumption etc, it is just the solar production that shows:

Toon P1 Power Solar
NaN Watt

I think this is being caused because Toon thinks my Qubino is a second 'meteradapter'

**Comment by cyberjunky** [comment]
@hosmancevic you need to check the json output (enable debug) to see which entries contain the Qubino data.

**Comment by hosmancevic** [comment]
Hi, you mean enabling debug on the toon? Will need to check how to do that. shouldn't be that difficult

**Comment by cyberjunky** [comment]
@hosmancevic no in Home Assistant, or just visit http://your_toon_ip:your_toon_port/hdrv_zwave?action=getDevices.json
With a web browser.

**Comment by hosmancevic** [comment]
Visiting that websites i can see these outputs for the Qubino smart meter:

"dev_8": {"uuid": "970cf4ec-37a5-4238-a3ca-e746b5ff1ab9", "name": "ZMNHTD1", "internalAddress": "8", "type": "ZMNHTD1", "supportsCrc": "1", "ccList": "5e 55 86 73 56 98 9f 72 5a 70 85 59 32 6c 7a", "supportedCC": "5e 55 86 73 56 98 9f 72 5a 70 85 59 32 6c 7a", "nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName": "ZMNHTD1", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "0.00", "CurrentVoltage": "234.70", "CurrentCurrent": "1.97", "TargetStatus": "-1"}, "dev_8.export": {"uuid": "02c1e8ab-58ff-48f6-ab4c-b410913b8761", "name": "ZMNHTD1_export", "internalAddress": "8.export", "type": "ZMNHTD1_export", "supportsCrc": "0", "nodeFlags": [], "CurrentElectricityQuantity": "800.00", "CurrentElectricityFlow": "454.10", "DeviceName": "ZMNHTD1_export"}}

**Comment by hosmancevic** [comment]
I tried adding this to the sensor.py, but it does not solve the issue;

                """zon op toon"""
            elif self._type == 'elecsolar':
                if 'dev_2.3' in energy:
                    self._state = energy["dev_2.3"]["CurrentElectricityFlow"]
                elif 'dev_3.3' in energy:
                    self._state = energy["dev_3.3"]["CurrentElectricityFlow"]
                elif 'dev_4.3' in energy:
                    self._state = energy["dev_4.3"]["CurrentElectricityFlow"]
                elif 'dev_8' in energy:
                    self._state = energy["dev_8"]["CurrentElectricityFlow"]
                elif 'dev_8.export' in energy:
                    self._state = energy["dev_8.export"]["CurrentElectricityFlow"]

                """zon op toon teller"""
            elif self._type == 'elecsolarcnt':
                if 'dev_2.3' in energy:
                    self._state = float(energy["dev_2.3"]["CurrentElectricityQuantity"])/1000
                elif 'dev_3.3' in energy:
                    self._state = float(energy["dev_3.3"]["CurrentElectricityQuantity"])/1000
                elif 'dev_4.3' in energy:
                    self._state = float(energy["dev_4.3"]["CurrentElectricityQuantity"])/1000
                elif 'dev_8' in energy:
                    self._state = float(energy["dev_8"]["CurrentElectricityQuantity"])/1000
                elif 'dev_8.export' in energy:
                    self._state = float(energy["dev_8.export"]["CurrentElectricityQuantity"])/1000

**Comment by cyberjunky** [comment]
@hosmancevic the layout names are different what happens if you add "8.export" ?

**Comment by hosmancevic** [comment]
Ah, looks like it did not work because dev_2.3 exists, so it does not go to the elif. Changed it to this:

                """zon op toon"""
            elif self._type == 'elecsolar':
                if 'dev_8.export' in energy:
                    self._state = energy["dev_8.export"]["CurrentElectricityFlow"]
                elif 'dev_2.3' in energy:
                    self._state = energy["dev_2.3"]["CurrentElectricityFlow"]
                elif 'dev_3.3' in energy:
                    self._state = energy["dev_3.3"]["CurrentElectricityFlow"]
                elif 'dev_4.3' in energy:
                    self._state = energy["dev_4.3"]["CurrentElectricityFlow"]

                """zon op toon teller"""
            elif self._type == 'elecsolarcnt':
                if 'dev_8.export' in energy:
                    self._state = float(energy["dev_8.export"]["CurrentElectricityQuantity"])/1000
                elif 'dev_2.3' in energy:
                    self._state = float(energy["dev_2.3"]["CurrentElectricityQuantity"])/1000
                elif 'dev_3.3' in energy:
                    self._state = float(energy["dev_3.3"]["CurrentElectricityQuantity"])/1000
                elif 'dev_4.3' in energy:
                    self._state = float(energy["dev_4.3"]["CurrentElectricityQuantity"])/1000

This seems to work
![toonsolar](https://user-images.githubusercontent.com/25821990/101490042-1497c100-3962-11eb-8444-b0143b919224.JPG)
Thank you for your help! This issue can be closed!
