### ISSUE TITLE
Values not "resetting" to zero when no consumption

### ISSUE THREAD

**Issue by DYLaKo** [cyberjunky/home-assistant-toon_smartmeter#15]
Within Home Assistant I have the following sensors which show this issue, but I assume it is for all sensors which output actual usage/production:

sensor.toon_p1_power_use_low
sensor.toon_p1_power_use_high
sensor.toon_gas_used_last_hour

Issue:
When there is no consumption on one of the above, the sensor keeps the last value received.
Example: When I use electricity within the low tariff and there is a switch to the high tariff, the sensor for the low tariff keeps the last "current" usage. This gives a wrong representation of the used electricity, the low tariff sensor should show "0" and not the last value.

Above also occurs for the gas usage. If using gas in the morning, the next hour the sensor is updated with the last usage for the previous hour. If there is no gas usage after that, the value of the last usage is shown until there is gas usage again.

**Comment by DYLaKo** [comment]
It seems the toon is still publishing the values. When requesting the information through the webbrowser with the url:
http://192.168.123.54:10080/hdrv_zwave?action=getDevices.json

I see the following for gas and electricity:
"CurrentGasFlow": "179.00"
"DeviceName": "HAE_METER_v3_6", "CurrentElectricityFlow": "691.00"

There is no gas usage at the moment and the lower tariff is not active at the moment.

**Comment by cyberjunky** [comment]
The gas value is for last hour, it doesn't reflect real time values because gas sensor only syncs every hour to save battery (it's wireless in gas meter)

**Comment by DYLaKo** [comment]
> The gas value is for last hour, it doesn't reflect real time values because gas sensor only syncs every hour to save battery (it's wireless in gas meter)
I know this, but it also shows a value if there was no gas usage in the last hour. It only updates if there was actual gas usage in the last hour.

**Comment by DYLaKo** [comment]
I rebooted the Toon by logging in through SSH and giving it the "reboot" command. If I check the info now through the URL: 
http://toon-ip:toon-port/hdrv_zwave?action=getDevices.json

"CurrentGasFlow": "179.00"
"DeviceName": "HAE_METER_v3_6", "CurrentElectricityFlow": "0.00" 

As mentioned, there is no gasflow now and not since 07:30 this morning,  so it seems it does not get an update that it is zero?
The power seems to have reset to zero after the reboot.

**Comment by cyberjunky** [comment]
So this is a Toon internal issue, it seems to simply reflect the info on the dashboard?

**Comment by DYLaKo** [comment]
> So this is a Toon internal issue, it seems to simply reflect the info on the dashboard?

Yes, so this issue can be closed. I'll be monitoring the Toon the coming days to see what happens there and if something strange occurs and also reflects in the JSON data, I will create a topic on the rooted Toon forum to see if they have a solution for it.
