### ISSUE TITLE
self._validateOutput at solar breaks all sensors

### ISSUE THREAD

**Issue by hosmancevic** [cyberjunky/home-assistant-toon_smartmeter#16]
Hi,

With the update my Zon op Toon broke again because i am using the Qubino smart meter.
When i change my sensor from this:

            """zon op toon"""
        elif self._type == 'elecsolar':
            if 'dev_8.export' in energy:
                self._state = energy["dev_8.export"]["CurrentElectricityFlow"]
            elif 'dev_2.3' in energy:
                self._state = energy["dev_2.3"]["CurrentElectricityFlow"]
            elif 'dev_3.3' in energy:
                self._state = energy["dev_3.3"]["CurrentElectricityFlow"]
            elif 'dev_4.3' in energy:
                self._state = energy["dev_4.3"]["CurrentElectricityFlow"]

            """zon op toon teller"""
        elif self._type == 'elecsolarcnt':
            if 'dev_8.export' in energy:
                self._state = float(energy["dev_8.export"]["CurrentElectricityQuantity"])/1000
            elif 'dev_2.3' in energy:
                self._state = float(energy["dev_2.3"]["CurrentElectricityQuantity"])/1000
            elif 'dev_3.3' in energy:
                self._state = float(energy["dev_3.3"]["CurrentElectricityQuantity"])/1000
            elif 'dev_4.3' in energy:
                self._state = float(energy["dev_4.3"]["CurrentElectricityQuantity"])/1000

to this:

				"""zon op toon"""
			elif self._type == 'elecsolar':
				if 'dev_8.export' in energy:
					self._state = self._validateOutput(energy["dev_8.export"]["CurrentElectricityFlow"])
				elif 'dev_2.3' in energy:
					self._state = self._validateOutput(energy["dev_2.3"]["CurrentElectricityFlow"])
				elif 'dev_3.3' in energy:
					self._state = self._validateOutput(energy["dev_3.3"]["CurrentElectricityFlow"])
				elif 'dev_4.3' in energy:
					self._state = self._validateOutput(energy["dev_4.3"]["CurrentElectricityFlow"])

				"""zon op toon teller"""
			elif self._type == 'elecsolarcnt':
				if 'dev_8.export' in energy:
					self._state = self._validateOutput(float(energy["dev_8.export"]["CurrentElectricityQuantity"])/1000)
				elif 'dev_2.3' in energy:
					self._state = self._validateOutput(float(energy["dev_2.3"]["CurrentElectricityQuantity"])/1000)
				elif 'dev_3.3' in energy:
					self._state = self._validateOutput(float(energy["dev_3.3"]["CurrentElectricityQuantity"])/1000)
				elif 'dev_4.3' in energy:
					self._state = self._validateOutput(float(energy["dev_4.3"]["CurrentElectricityQuantity"])/1000)

All my sensor break. so also the not Toon related. How can i solve this?

**Comment by cyberjunky** [comment]
@hosmancevic I'm sorry for that, didn't have time yet to figure out/implement a better way to address the different device numbers, what is in the ha log? I suspect some sort of indent or other type slipped in.

**Comment by cyberjunky** [comment]
Ticket went inactive, closing, please reopen if needed.
