### ISSUE TITLE
Toon inactive

### ISSUE THREAD

**Issue by benalla** [cyberjunky/home-assistant-toon_smartmeter#17]
Followed all the steps. 
But the card in Lovelace keeps ‘ inactive’ .

What am I missing?

![D6E9C6A9-09EB-45F2-BEA1-6D027994FE48](https://user-images.githubusercontent.com/3511603/112702390-9c62f600-8e93-11eb-97b6-5d993f4b0f92.jpeg)

![625CB51A-2BCF-4F53-B15F-54896066FE83](https://user-images.githubusercontent.com/3511603/112702244-1ba3fa00-8e93-11eb-9515-82fc5d8bfe49.jpeg)

**Comment by cyberjunky** [comment]
Ticket went inactive too, if you have any debug logging, please reopen.
