### ISSUE TITLE
Energy Usage with Zon op Toon

### ISSUE THREAD

**Issue by itguy013** [cyberjunky/home-assistant-toon_smartmeter#18]
Hi,

Since a few days, i have Zon op Toon with a Toon 2 and a Qubino Smart Meter. It works all fine. I have 1 request about this.
On the Toon you can create a tile with StroomVebruik Nu. This is a tile which is looking on what your house is using ex solar production. Like this:

Solar panel gerating minus What is been exported to the grid =  Usage of your house. 

Is it possible to see what your house is using in HA? Now u see with power use low/high 0 because it's exporting all the energy. But i want to see what the house is using without solar production on HA. 

see the attachment with an example of what I mean. Hope someone can help. 

https://ibb.co/kXHZrWY

**Comment by cyberjunky** [comment]
You mean something like this, which I use

![image](https://user-images.githubusercontent.com/5447161/114166207-bab60080-992d-11eb-977c-6c71d81b3753.png)
```yaml
  - platform: template
    sensors:
      stroom_verbruik:
        friendly_name: "Stroom Verbruik"
        unit_of_measurement: "Watt"
        value_template: >
          {{ ( (states('sensor.toon_p1_power_use_low')|float) + (states('sensor.toon_p1_power_use_high')|float) ) }}
      stroom_levering:
        friendly_name: "Stroom Levering"
        unit_of_measurement: "Watt"
        value_template: >
          {{ ( (states('sensor.toon_p1_power_prod_low')|float) + (states('sensor.toon_p1_power_prod_high')|float) ) }}

**Comment by itguy013** [comment]
Yeah something like that, but i'm using another card named type: tesla-style-solar-power-card
There you need a sensor which is current production minus export = total usage. If i use your template sensor, my value is getting 0 because netto there is no usage. If the production is higher then my usage, the value of both power_use_low and power_use_high getting zero until i use more then i produce.

**Comment by cyberjunky** [comment]
@harisosmancevic it's called power-wheel card

https://github.com/gurbyz/power-wheel-card/tree/master
