### ISSUE TITLE
Geen laag tarief waarden meer.

### ISSUE THREAD

**Issue by gerritjonker** [cyberjunky/home-assistant-toon_smartmeter#21]
Smartmeter versie 1.0.13
Home-assistant versie 2021.6.6

sensor.toon_p1_power_use_low en sensor.toon_p1_power_use_cnt_low werken niet meer. 
Geen log vermeldingen.

Kan het komen door de discovery? Laag tarief is alleen beschikbaar tussen 23:00 en 6:00 uur en in de weekeinden.

**Comment by cyberjunky** [comment]
Zou kunnen als die een afwijkende status hebben, ben je in de gelegengheid om de json te pasten?
Dan kijk ik er naar.

http://TOON_IP:TOON_PORT/hdrv_zwave?action=getDevices.json

**Comment by gerritjonker** [comment]
`{"dev_settings_device": {"uuid": "4016e911-55eb-4fe2-b4f4-d66c50600be9", "name": "settings_device", "internalAddress": "settings_device", "type": "settings_device"}, "dev_2": {"uuid": "db50fb14-b097-4ea6-9117-3971c9017751", "name": "HAE_METER_v3", "internalAddress": "2", "type": "HAE_METER_v3", "supportsCrc": "1", "ccList": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "supportedCC": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName": "HAE_METER_v3", "CurrentSensorStatus": "UNKNOWN"}, "dev_2.1": {"uuid": "b4dedc75-2660-4cb9-8e0e-1236591f2872", "name": "HAE_METER_v3_1", "internalAddress": "2.1", "type": "HAE_METER_v3_1", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentGasFlow": "6.00", "CurrentGasQuantity": "2803309.00", "DeviceName": "HAE_METER_v3_1", "CurrentSensorStatus": "OPERATIONAL"}, "dev_2.2": {"uuid": "e4809709-0060-4bc0-9970-14a288a6f550", "name": "HAE_METER_v3_2", "internalAddress": "2.2", "type": "HAE_METER_v3_2", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_2", "CurrentSensorStatus": "UNKNOWN", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_2.3": {"uuid": "0a407c34-b567-4a14-ad2c-ed2d21369a2f", "name": "HAE_METER_v3_3", "internalAddress": "2.3", "type": "HAE_METER_v3_3", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_3", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN", "CurrentSensorStatus": "UNKNOWN"}, "dev_2.4": {"uuid": "4d99e81d-5051-46f7-927a-9f8da35f71c9", "name": "HAE_METER_v3_4", "internalAddress": "2.4", "type": "HAE_METER_v3_4", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_4", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "3349003.00", "CurrentSensorStatus": "OPERATIONAL"}, "dev_2.5": {"uuid": "9537cdee-3c05-4c2d-a3e4-40e6f3c018b0", "name": "HAE_METER_v3_5", "internalAddress": "2.5", "type": "HAE_METER_v3_5", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_5", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "1.00", "CurrentSensorStatus": "UNKNOWN"}, "dev_2.6": {"uuid": "205bd24e-140c-40e4-956c-5df0a76e211c", "name": "HAE_METER_v3_6", "internalAddress": "2.6", "type": "HAE_METER_v3_6", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_6", "CurrentElectricityFlow": "627.00", "CurrentElectricityQuantity": "3894662.00", "CurrentSensorStatus": "UNKNOWN"}, "dev_2.7": {"uuid": "54946413-4df2-4d4f-8139-3aa563524859", "name": "HAE_METER_v3_7", "internalAddress": "2.7", "type": "HAE_METER_v3_7", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_7", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "0.00", "CurrentSensorStatus": "UNKNOWN"}, "dev_2.8": {"uuid": "2c501ada-2c05-44f0-b22a-cbb9a2becf19", "name": "HAE_METER_v3_8", "internalAddress": "2.8", "type": "HAE_METER_v3_8", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_8", "CurrentHeatQuantity": "NaN", "CurrentSensorStatus": "UNKNOWN", "CurrentHeatFlow": "NaN"}}`

**Comment by kurniawan77** [comment]
Smartmeter versie 1.0.13
Home-assistant versie 2021.6.6
Hier ook geen laagtarief te zien maar wel in JSON ("DeviceName":"HAE_METER_v2_5","CurrentElectricityFlow":"162.00"):

{
   "dev_settings_device":{
      "uuid":"d9b65ba2-2fa0-4ffc-8e55-9038447d2cef",
      "name":"settings_device",
      "internalAddress":"settings_device",
      "type":"settings_device"
   },
   "dev_3":{
      "uuid":"e59bd482-dae0-4101-b382-6b2f5f731248",
      "name":"HAE_METER_v2",
      "internalAddress":"3",
      "type":"HAE_METER_v2",
      "supportsCrc":"1",
      "ccList":"22 3c 3d 3e 56 60 70 72 7a 86 8b 73",
      "supportedCC":"22 3c 3d 3e 56 60 70 72 7a 86 8b 73",
      "nodeFlags":[
         
      ],
      "IsConnected":"1",
      "HealthValue":"10",
      "DeviceName":"HAE_METER_v2",
      "CurrentSensorStatus":"UNKNOWN"
   },
   "dev_3.1":{
      "uuid":"b4d372e9-073c-4010-9bae-11bc66a78a63",
      "name":"HAE_METER_v2_1",
      "internalAddress":"3.1",
      "type":"HAE_METER_v2_1",
      "supportsCrc":"0",
      "ccList":"3c 3d 3e 72 86",
      "supportedCC":"3c 3d 3e 72 86",
      "nodeFlags":[
         
      ],
      "CurrentGasFlow":"0.00",
      "CurrentGasQuantity":"8474165.00",
      "DeviceName":"HAE_METER_v2_1",
      "CurrentSensorStatus":"OPERATIONAL"
   },
   "dev_3.2":{
      "uuid":"da74a1ae-58d0-4368-bd5f-fc9e6cc35c06",
      "name":"HAE_METER_v2_2",
      "internalAddress":"3.2",
      "type":"HAE_METER_v2_2",
      "supportsCrc":"0",
      "ccList":"3c 3d 3e 72 86",
      "supportedCC":"3c 3d 3e 72 86",
      "nodeFlags":[
         
      ],
      "DeviceName":"HAE_METER_v2_2",
      "CurrentSensorStatus":"UNKNOWN",
      "CurrentElectricityFlow":"NaN",
      "CurrentElectricityQuantity":"NaN"
   },
   "dev_3.3":{
      "uuid":"7dc16905-b9f4-4c13-8810-9a78b41f17a4",
      "name":"HAE_METER_v2_3",
      "internalAddress":"3.3",
      "type":"HAE_METER_v2_3",
      "supportsCrc":"0",
      "ccList":"3c 3d 3e 72 86",
      "supportedCC":"3c 3d 3e 72 86",
      "nodeFlags":[
         
      ],
      "DeviceName":"HAE_METER_v2_3",
      "CurrentElectricityFlow":"0.00",
      "CurrentElectricityQuantity":"11021290.00",
      "CurrentSensorStatus":"OPERATIONAL"
   },
   "dev_3.4":{
      "uuid":"5c4b761d-3a20-4cfb-b9ac-1fef790f1839",
      "name":"HAE_METER_v2_4",
      "internalAddress":"3.4",
      "type":"HAE_METER_v2_4",
      "supportsCrc":"0",
      "ccList":"3c 3d 3e 72 86",
      "supportedCC":"3c 3d 3e 72 86",
      "nodeFlags":[
         
      ],
      "DeviceName":"HAE_METER_v2_4",
      "CurrentElectricityFlow":"0.00",
      "CurrentElectricityQuantity":"0.00",
      "CurrentSensorStatus":"UNKNOWN"
   },
   "dev_3.5":{
      "uuid":"3b1bab83-1850-434d-a0b9-2ef54ba5e69a",
      "name":"HAE_METER_v2_5",
      "internalAddress":"3.5",
      "type":"HAE_METER_v2_5",
      "supportsCrc":"0",
      "ccList":"3c 3d 3e 72 86",
      "supportedCC":"3c 3d 3e 72 86",
      "nodeFlags":[
         
      ],
      "DeviceName":"HAE_METER_v2_5",
      "CurrentElectricityFlow":"162.00",
      "CurrentElectricityQuantity":"9633289.00",
      "CurrentSensorStatus":"UNKNOWN"
   },
   "dev_3.6":{
      "uuid":"857b8a20-bdc5-4bae-b196-1d0bf2d72a6d",
      "name":"HAE_METER_v2_6",
      "internalAddress":"3.6",
      "type":"HAE_METER_v2_6",
      "supportsCrc":"0",
      "ccList":"3c 3d 3e 72 86",
      "supportedCC":"3c 3d 3e 72 86",
      "nodeFlags":[
         
      ],
      "DeviceName":"HAE_METER_v2_6",
      "CurrentElectricityFlow":"0.00",
      "CurrentElectricityQuantity":"0.00",
      "CurrentSensorStatus":"UNKNOWN"
   }
}

**Comment by cyberjunky** [comment]
@gerritjonker 
```
  'dev_2.6': {
    'uuid': '205bd24e-140c-40e4-956c-5df0a76e211c',
    'name': 'HAE_METER_v3_6',
    'internalAddress': '2.6',
    'type': 'HAE_METER_v3_6',
    'supportsCrc': '0',
    'ccList': '5e 59 85 8e 3c 3d 3e',
    'supportedCC': '5e 59 85 8e 3c 3d 3e',
    'nodeFlags': [
      
    ],
    'DeviceName': 'HAE_METER_v3_6',
    'CurrentElectricityFlow': '627.00',
    'CurrentElectricityQuantity': '3894662.00',
    'CurrentSensorStatus': 'UNKNOWN'
  },  'dev_2.6': {
    'uuid': '205bd24e-140c-40e4-956c-5df0a76e211c',
    'name': 'HAE_METER_v3_6',
    'internalAddress': '2.6',
    'type': 'HAE_METER_v3_6',
    'supportsCrc': '0',
    'ccList': '5e 59 85 8e 3c 3d 3e',
    'supportedCC': '5e 59 85 8e 3c 3d 3e',
    'nodeFlags': [
      
    ],
    'DeviceName': 'HAE_METER_v3_6',
    'CurrentElectricityFlow': '627.00',
    'CurrentElectricityQuantity': '3894662.00',
    'CurrentSensorStatus': 'UNKNOWN'
  },
```
Ga ervan uit dat dit je laag waardes zijn.
Vaag waarom sensorstatus daarvan unknown is, ik ga op zoek naar andere manier om ongebruikte sensoren te detecteren, wellicht die zonder waardes overslaan.

**Comment by cyberjunky** [comment]
@kurniawan77 Yeah, sensorstatus is unknown, I have made a fix to check on NaN values to detect inactive sensors.
Hope this works better for all.

**Comment by kurniawan77** [comment]
@cyberjunky The fix seems to work fine... getting some results back when i updated yesterday

**Comment by gerritjonker** [comment]
Ik kan dit bevestigen. Ik zie geen problemen meer.

Bedankt voor de fix!

**Comment by cyberjunky** [comment]
Jullie ook bedankt voor de input
