### ISSUE TITLE
Expected data source not listed

### ISSUE THREAD

**Issue by arcidodo** [cyberjunky/home-assistant-toon_smartmeter#22]
Hi,

i like the new energy feature of version 2021.8.0 see demo here: 
https://demo.home-assistant.io/#/energy

is it possible to get this working with this intergration? here is the documentation of the needed feature:
https://www.home-assistant.io/more-info/statistics/

https://www.home-assistant.io/blog/2021/08/04/home-energy-management/

**Comment by davemenkehorst** [comment]
Hi! Second this. I want to use the energy feature but it's missing my Toon intergration

https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics
Thanks for the great work
