### ISSUE TITLE
Missing data for new energy integration

### ISSUE THREAD

**Issue by Dutchy-79** [cyberjunky/home-assistant-toon_smartmeter#24]
Hi,

According to someone on a facebook group I need 4 additional sensors to make rooted Toon work with the new HA energy integration.

> ik heb via Toon, heb overigens geen zonnepanelen maar zie de optie voorbij komen. Bij de toon integratie zijn een aantal entiten standaard uitgeschakeld. Betreft de entiteiten met je meterstanden, deze moet inschakelen en heb je nodig voor je verbruik.
> 
> Grid:
> 
> sensor.electricity_meter_feed_in_tariff_1
> sensor.electricity_meter_feed_in_tariff_2
> 
> Opwekken: entiteiten van je omvormer, anders kan je deze volgens mij gebruiken, maar wordt hier dan alleen geregistreerd wat je terug levert aan het net. Je weet dan niet wat je zelf verbruikt.
> 
> sensor.electricity_meter_feed_out_tariff_1
> sensor.electricity_meter_feed_out_tariff_2

**Comment by cyberjunky** [comment]
@Dutchy-79 I released 1.0.15, can you have a look if it works?

**Comment by Dutchy-79** [comment]
Hi,

Thank you, that seems to be fine.

Op do 5 aug. 2021 19:53 schreef Ron Klinkien ***@***.***>:

**Comment by Dutchy-79** [comment]
Working great so far. Thanks for your help.
