### ISSUE TITLE
home assistant long term statistics

### ISSUE THREAD

**Issue by RaJeronimo** [cyberjunky/home-assistant-toon_smartmeter#28]
Hi,
First of all. Thanxs for this great component! 
I have a question. In the new energy update home assistant requests one of two state classes:
measurement or total_increasing. 
In the latest update of this component all entities are changed to measurement. Doesn't the cumulative entities (for example P1 Power Use Cnt High) need te be total_increasing ? 
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

i know i can change this setting in customize.yaml but i was curious if i'm correct?

**Comment by djansen1987** [comment]
That seems to be recently added as it was not available if i am correct during the update of the component.

**Comment by djansen1987** [comment]
Has been added 9 days ago

https://github.com/home-assistant/developers.home-assistant/pull/1026/files

**Comment by cyberjunky** [comment]
As far as I know it's in beta, so I cannot add it now to the stable component.
Will do some preparations though.

**Comment by cyberjunky** [comment]
Please try Release 1.0.18 it will appear in HACS shortly
Also added gas sensors for dashboard

**Comment by RaJeronimo** [comment]
Thnxs
