### ISSUE TITLE
Database gets broken when toon reboots

### ISSUE THREAD

**Issue by arcidodo** [cyberjunky/home-assistant-toon_smartmeter#29]
When i restart the toon, the database gets corrupted. 

i cannot acces home assistant anymore but this is in the logfile: 

`Logger: homeassistant.components.websocket_api.messages
Source: components/websocket_api/messages.py:82
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:04:56 (69 occurrences)
Last logged: 20:36:52

Unable to serialize to JSON. Bad data found at $.event(Event: state_changed).data.new_state(State: sensor.stats).attributes.mean=nan(<class 'float'>, $.event(Event: state_changed).data.new_state(State: sensor.stats).attributes.standard_deviation=nan(<class 'float'>, $.event(Event: state_changed).data.new_state(State: sensor.stats).attributes.variance=nan(<class 'float'>, $.event(Event: state_changed).data.new_state(State: sensor.stats).attributes.total=nan(<class 'float'>, $.event(Event: state_changed).data.new_state(State: sensor.stats).attributes.change=nan(<class 'float'>, $.event(Event: state_changed).data.new_state(State: sensor.stats).attributes.average_change=nan(<class 'float'>, $.event(Event: state_changed).data.new_state(State: sensor.stats).attributes.change_rate=nan(<class 'float'>
Unable to serialize to JSON. Bad data found at $.result[34](State: sensor.stats).attributes.mean=nan(<class 'float'>, $.result[34](State: sensor.stats).attributes.standard_deviation=nan(<class 'float'>, $.result[34](State: sensor.stats).attributes.variance=nan(<class 'float'>, $.result[34](State: sensor.stats).attributes.total=nan(<class 'float'>`

My guess is the "NaN value...

**Comment by cyberjunky** [comment]
Which version of the Toon integration do you run?
All nan values are normally rewritten to 0

**Comment by arcidodo** [comment]
latest version with the New energy integration. 

Ill try tonight to force this issue again, to find out witch value it is.
