### ISSUE TITLE
Electricity production is missing

### ISSUE THREAD

**Issue by Ysbrand** [cyberjunky/home-assistant-toon_smartmeter#3]
Hi,

It seems that my Toon is using different P1 devices for produced energy
LT: 3.7
NT: 3.5

I've modified the code to:
```
                if dev['type'] in ['elec_received_lt', 'HAE_METER_v2_6', 'HAE_METER_v3_7']:
                    self._dev_id['elecprodflowlow'] = key
                    self._dev_id['elecprodcntlow'] = key

                if dev['type'] in ['elec_received_nt', 'HAE_METER_v2_4', 'HAE_METER_v3_5']:
                    self._dev_id['elecprodflowhigh'] = key
                    self._dev_id['elecprodcnthigh'] = key
```
And that seems to be working.

What I'm still missing is the actual produced watts coming from the panels. In my case this is HAE_METER_v3_3, but I'm not sure where that is supposed to go in the code.

**Comment by DaLassOnline** [comment]
I am having the same issue, no produced energy is shown. If I read the data directly from the rooted Toon by using parts of your DSMR python script, I see that the devices in the P1 data differ from the settings in your code. Below you will find my output, maybe you can use it to optimize your component. (replaced some uuid codes with asterisks).

Gas:
```
'dev_2.1': {'uuid': '***********************',
 'name': 'HAE_METER_v3_1',
 'internalAddress': '2.1',
 'type': 'HAE_METER_v3_1',
 'supportsCrc': '0',
 'ccList': '************************',
 'supportedCC': '*******************',
 'nodeFlags': [], 'CurrentGasFlow': '72.00',
 'CurrentGasQuantity': '6055367.00',
 'DeviceName': 'HAE_METER_v3_1',
 'CurrentSensorStatus': 'OPERATIONAL'},
```

Electricity used from the grid, peak:
```
'dev_2.4': {'uuid': '**************************',
 'name': 'HAE_METER_v3_4',
 'internalAddress': '2.4',
 'type': 'HAE_METER_v3_4',
 'supportsCrc': '0',
 'ccList': '********************,
 'supportedCC': '**********************',
 'nodeFlags': [],
 'DeviceName': 'HAE_METER_v3_4',
 'CurrentElectricityFlow': '325.00',
 'CurrentElectricityQuantity': '7968634.00',
 'CurrentSensorStatus': 'OPERATIONAL'},
```

Electricity used from the grid, off-peak:
```
 'dev_2.6': {'uuid': '**********************************',
 'name': 'HAE_METER_v3_6',
 'internalAddress': '2.6',
 'type': 'HAE_METER_v3_6',
 'supportsCrc': '0',
 'ccList': '*********************************',
 'supportedCC': '************************',
 'nodeFlags': [],
 'DeviceName': 'HAE_METER_v3_6',
 'CurrentElectricityFlow': '0.00',
 'CurrentElectricityQuantity': '7106822.00',
 'CurrentSensorStatus': 'OPERATIONAL'},
```

Electricity produced and delivered back to the grid, peak:
```
 'dev_2.5': {'uuid': '***************************************',
 'name': 'HAE_METER_v3_5',
 'internalAddress': '2.5',
 'type': 'HAE_METER_v3_5',
 'supportsCrc': '0',
 'ccList': '******************************',
 'supportedCC': '********************************',
 'nodeFlags': [],
 'DeviceName': 'HAE_METER_v3_5',
 'CurrentElectricityFlow': '0.00',
 'CurrentElectricityQuantity': '1082525.00',
 'CurrentSensorStatus': 'OPERATIONAL'},
```

Electricity produced and delivered back to the grid, off-peak:
```
 'dev_2.7': {'uuid': '***********************',
 'name': 'HAE_METER_v3_7',
 'internalAddress': '2.7',
 'type': 'HAE_METER_v3_7',
 'supportsCrc': '0',
 'ccList': '***********************',
 'supportedCC': '**********************',
 'nodeFlags': [],
 'DeviceName': 'HAE_METER_v3_7',
 'CurrentElectricityFlow': '0.00',
 'CurrentElectricityQuantity': '481432.00',
 'CurrentSensorStatus': 'OPERATIONAL'},
```

**Comment by cyberjunky** [comment]
@DaLassOnline  @Ysbrand  It took a while but can you check if version 1.0.3 fixes your problems, it should appear in HACS any minute. Thanks!

**Comment by Ysbrand** [comment]
Thanks Ron for looking into this.
The produced energy issue seems to be fixed, thanks for that.

It appears to me that the solar readings are not fixed. I've hardcoded it now as follows:

            elif self._type == 'elecsolar':
                if 'dev_3.3' in energy:
                    self._state = energy["dev_3.3"]["CurrentElectricityFlow"]
                elif 'dev_4.3' in energy:
                    self._state = energy["dev_4.3"]["CurrentElectricityFlow"]

            elif self._type == 'elecsolarcnt':
                if 'dev_3.3' in energy:
                    self._state = float(energy["dev_3.3"]["CurrentElectricityQuantity"])/1000
                elif 'dev_4.3' in energy:
                    self._state = float(energy["dev_4.3"]["CurrentElectricityQuantity"])/1000

(Replaced dev_2.3 with dev_3.3, obviously that voids the cases in which 2_3 is needed

**Comment by cyberjunky** [comment]
@Ysbrand can you try version 1.0.6? 
It will appear in HACS soon or you can download latest sensor.py to overwrite yours.

**Comment by Ysbrand** [comment]
Thanks Ron for fixing this!
(I installed the new version last night, but obviously at that time there was no sunshine, hence the delayed report).
