### ISSUE TITLE
Changes for HA 2021.9

### ISSUE THREAD

**Issue by bafplus** [cyberjunky/home-assistant-toon_smartmeter#30]
Some (breaking) changes for version 2021.9 of HA:

- Volume for gas is changed from "m3" to "m³". need to change that to make the sensor.toon_gas_used_cnt available for the recorder and energy dashboard.
- Energy is still working but has a conversion that i could find myself: "Onverwachte state class
De volgende entiteiten hebben niet de verwachte state class "total_increasing"
sensor.toon_p1_power_use_cnt_high (measurement)
sensor.toon_p1_power_use_cnt_low (measurement)"

**Comment by cyberjunky** [comment]
Thanks, I will adapt the integration soon.

**Comment by bafplus** [comment]
Great! Cant wait! :-)

**Comment by gerthass** [comment]
Same for me. (just adding another example)

` Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:213
Integration: Sensor (documentation, issues)
First occurred: 4:16:36 PM (5 occurrences)
Last logged: 4:16:36 PM

    Entity sensor.toon_p1_power_use_cnt (<class 'custom_components.toon_smartmeter.sensor.ToonSmartMeterSensor'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
    Entity sensor.toon_p1_power_use_cnt_low (<class 'custom_components.toon_smartmeter.sensor.ToonSmartMeterSensor'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
    Entity sensor.toon_p1_power_use_cnt_high (<class 'custom_components.toon_smartmeter.sensor.ToonSmartMeterSensor'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
    Entity sensor.toon_p1_power_prod_cnt_low (<class 'custom_components.toon_smartmeter.sensor.ToonSmartMeterSensor'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
    Entity sensor.toon_p1_power_prod_cnt_high (<class 'custom_components.toon_smartmeter.sensor.ToonSmartMeterSensor'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
`

**Comment by Steefph** [comment]
Also the state_class should be set to total_increasing :)

**Comment by cyberjunky** [comment]
Please try Release 1.0.18 it will appear in HACS shortly
Also added gas sensors for dashboard

**Comment by Steefph** [comment]
@cyberjunky seems to be working fine

**Comment by bafplus** [comment]
> Please try Release 1.0.18 it will appear in HACS shortly
> Also added gas sensors for dashboard

Updating as we speak :-)

**Comment by bafplus** [comment]
Seems to work, will know in a few hours if recording history is working correctly.

**Comment by Steefph** [comment]
@bafplus mine already shows the correct info of the last 2 days.

**Comment by bafplus** [comment]
> @bafplus mine already shows the correct info of the last 2 days.

Im using mariaDB, i just checked and i dont have any history or gas sensors in it.
Should it register the sensor(data) there automaticly?
(i only state "recorder:" in my config.yaml so it "should" record all available sensors since i dont specify any entities.)

**Comment by Steefph** [comment]
I'm using InfluxDB and had the values already in there. Perhaps that's why I see them already.

**Comment by bafplus** [comment]
The sensors just registered in the DB, So i figure its just like a first install and needs at least a few measurements. Well, its doing something so hopefull :-)

**Comment by bafplus** [comment]
it works! thanks @cyberjunky for the quick fix.

**Comment by Janver448** [comment]
I have updated on my HA 2021.8.8, to the Smart Meter 1.0.18 after the update most of the sensor readings are lost. Checked the config which shows the following error.  Controleer uw configuratie als u onlangs wijzigingen hebt aangebracht en zeker wilt weten dat ze geldig zijn
Ongeldige configuratie 
CONTROLEER CONFIGURATIE
  Platform error sensor.toon_smartmeter - cannot import name 'STATE_CLASS_TOTAL_INCREASING' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)

**Comment by cyberjunky** [comment]
@Janver448 you need to downgrade to 1.0.17, 1.0.18 is only working om 2021.9.x

**Comment by Janver448** [comment]
Thank for reply, will leave it on 1.0.18 and update HA when 2021.9.0 is available for update. Perhaps, I have missed something but have not seen anything about the compatibility on different HA versions. It was not noticed the 1.0.18 was not backwards compatible with previous HA versions. But most important, thanks for the good work, still keeping the development on the Toon Smart Meter alive with new features. Many users will be thankful.

**Comment by gerthass** [comment]
> Please try Release 1.0.18 it will appear in HACS shortly
> Also added gas sensors for dashboard

Fixed it

**Comment by Janver448** [comment]
Updated HA from 2021.8.8 to 2021.9.1 the 1.0.18 works without any problem. Validate config shows no error😀
