### ISSUE TITLE
unknown unit m3

### ISSUE THREAD

**Issue by megapeer** [cyberjunky/home-assistant-toon_smartmeter#32]
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:229
Integration: Sensor (documentation, issues)
First occurred: 22:12:34 (2 occurrences)
Last logged: 22:12:34

sensor.toon_gas_used_last_hour has unknown unit m3
sensor.toon_gas_used_cnt has unknown unit m3

**Comment by bafplus** [comment]
Fixed in latest update due to upgrade of HA 2021.9.
Make sure both HA and Toon plugin are updated.

**Comment by megapeer** [comment]
thanks
