### ISSUE TITLE
Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. 

### ISSUE THREAD

**Issue by gerritjonker** [cyberjunky/home-assistant-toon_smartmeter#35]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:213 
Integration: Sensor (documentation, issues) 
First occurred: 17:22:46 (3 occurrences) 
Last logged: 17:22:46

Entity sensor.toon_gas_used_cnt_cost (<class 'homeassistant.components.energy.sensor.EnergyCostSensor'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+energy%22
Entity sensor.toon_p1_power_use_cnt_low_cost (<class 'homeassistant.components.energy.sensor.EnergyCostSensor'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+energy%22
Entity sensor.toon_p1_power_use_cnt_high_cost (<class 'homeassistant.components.energy.sensor.EnergyCostSensor'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+energy%22

**Comment by cyberjunky** [comment]
Fixed in latest versions
