### ISSUE TITLE
Home Assistant Brands

### ISSUE THREAD

**Issue by djansen1987** [cyberjunky/home-assistant-toon_smartmeter#36]
Hi @cyberjunky ,

Ik kwam er achter dat je components nog niet toegevoegd waren aan brands. Als bedankje voor het onderhouden van de componenten heb ik hiervoor een voorzet gemaakt en als je je hierin kan vinden kan ik een pull request aanvragen om ze door te voeren.  Hoor graag wat je er van vindt. (mocht je het niks vinden ook geen probleem!)

https://github.com/djansen1987/brands/commit/6a777f4d492bf84a4db85e750ae9421d97af4952#diff-b9a831a9ce2a65bfcf5ea4c788bc4e8a2c0c38bec072760ee9aff88ed5bd6307

### Voorbeelden:

![toon_boilerstatus](https://github.com/djansen1987/brands/blob/6a777f4d492bf84a4db85e750ae9421d97af4952/custom_integrations/toon_boilerstatus/logo@2x.png?raw=true"toon_boilerstatus")

![toon_climate](https://github.com/djansen1987/brands/blob/6a777f4d492bf84a4db85e750ae9421d97af4952/custom_integrations/toon_climate/logo@2x.png?raw=true"toon_climate")

![toon_smartmeter](https://github.com/djansen1987/brands/blob/6a777f4d492bf84a4db85e750ae9421d97af4952/custom_integrations/toon_smartmeter/logo@2x.png?raw=true"toon_smartmeter")

![toon_boilerstatus](https://github.com/djansen1987/brands/blob/6a777f4d492bf84a4db85e750ae9421d97af4952/custom_integrations/toon_boilerstatus/icon@2x.png?raw=true "toon_boilerstatus")

![toon_climate](https://github.com/djansen1987/brands/blob/6a777f4d492bf84a4db85e750ae9421d97af4952/custom_integrations/toon_climate/icon@2x.png?raw=true"toon_climate")

![toon_smartmeter](https://github.com/djansen1987/brands/blob/6a777f4d492bf84a4db85e750ae9421d97af4952/custom_integrations/toon_smartmeter/icon@2x.png?raw=true "toon_smartmeter")

**Comment by cyberjunky** [comment]
Hi, that's very kind.
But i fear they won't allow them, since it may only contain the brand itself (I know there are others not follwoing this)
So we maybe we should  copy the ones from the official Toon integration.
You can try though...

**Comment by djansen1987** [comment]
Hi, 
Did not know that. Will have a read to see what the rules are.

**Comment by djansen1987** [comment]
Had a read on https://github.com/home-assistant/brands but could not really find anything on why it would not be possible. There is an advisement for core integration to create symlinks but this is not possible for custom components.

**Comment by cyberjunky** [comment]
I know, I couldn't find them as well, but look at the comments on an earlier PR from me.
https://github.com/home-assistant/brands/pull/2758
