### ISSUE TITLE
Zon op Toon

### ISSUE THREAD

**Issue by mehmetakin1996** [cyberjunky/home-assistant-toon_smartmeter#39]
@cyberjunky 
Kan jij nog zodra je tijd hebt kijken naar hoe ik mijn Zon op Toon gegevens in mijn Dashboard kan zetten in HA?
Ik hoor het van je.

**Comment by IgorYbema** [comment]
@mehmetakin1996 heb jij een Qubino zonoptoon meet module?
Zo ja, kan je dan even de output van http://toon-ip-adres/hdrv_zwave?action=getDevices.json hier posten?

**Comment by cyberjunky** [comment]
> @cyberjunky Kan jij nog zodra je tijd hebt kijken naar hoe ik mijn Zon op Toon gegevens in mijn Dashboard kan zetten in HA? Ik hoor het van je.

@mehmetakin1996 @IgorYbema 
Het probleem dat je had was volgens mij dat je meerdere adapters had, klopt dat?
Dat maakte heb wat minder standaard... wellicht kan Igor meedenken ;-)

**Comment by IgorYbema** [comment]
Ik denk zo'n qubino zwave meet module voor zonoptoon. Zal eens kijken hoe dat ook mee kan

**Comment by IgorYbema** [comment]
En niet vergeten dat de qubino ook als consuptie meter gebruikt wordt in sommige situatie  (en dus niet voor zonoptoon)

**Comment by mehmetakin1996** [comment]
Hoe kan ik zo een debug info weer gaan activeren.
Ik had het ooit weer verwijderd.
@IgorYbema  en @cyberjunky

**Comment by IgorYbema** [comment]
Wat ik hier boven post... even die url in je browser, toon ip adres invullen en resultaat hier posten.

**Comment by mehmetakin1996** [comment]
Yes! zie hieronder!

{"dev_settings_device": {"uuid": "ef7ca589-1c0a-4553-a19a-f96beafee75a", "name": "settings_device", "internalAddress": "settings_device", "type": "settings_device"}, "dev_2": {"uuid": "687aacff-078c-4866-806a-94408595aa70", "name": "HAE_METER_v3", "internalAddress": "2", "type": "HAE_METER_v3", "supportsCrc": "1", "ccList": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "supportedCC": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName": "HAE_METER_v3", "CurrentSensorStatus": "UNKNOWN"}, "dev_2.1": {"uuid": "fe97aea5-3b90-4e54-a5f6-793e2221eaf4", "name": "HAE_METER_v3_1", "internalAddress": "2.1", "type": "HAE_METER_v3_1", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "WARNING", "CurrentGasFlow": "3.00", "CurrentGasQuantity": "2874193.00", "DeviceName": "HAE_METER_v3_1"}, "dev_2.2": {"uuid": "98f918e9-9511-4ac2-9af7-958081a35ea6", "name": "HAE_METER_v3_2", "internalAddress": "2.2", "type": "HAE_METER_v3_2", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_2", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_2.3": {"uuid": "7162c8d2-3b0a-4271-b44c-dd7353cce730", "name": "HAE_METER_v3_3", "internalAddress": "2.3", "type": "HAE_METER_v3_3", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_3", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_2.4": {"uuid": "3e3d011a-e82f-4f21-9658-8a574d4b2a54", "name": "HAE_METER_v3_4", "internalAddress": "2.4", "type": "HAE_METER_v3_4", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "WARNING", "DeviceName": "HAE_METER_v3_4", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "6510696.00"}, "dev_2.5": {"uuid": "183e9d51-248d-4cd1-a507-4816f9bd5deb", "name": "HAE_METER_v3_5", "internalAddress": "2.5", "type": "HAE_METER_v3_5", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_5", "CurrentElectricityFlow": "1626.00", "CurrentElectricityQuantity": "1770603.00"}, "dev_2.6": {"uuid": "610c0238-8b84-489c-bda6-21e3e08ed9e4", "name": "HAE_METER_v3_6", "internalAddress": "2.6", "type": "HAE_METER_v3_6", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_6", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "7359947.00"}, "dev_2.7": {"uuid": "60fdc89b-40f9-488a-85ed-3fb0d36061f4", "name": "HAE_METER_v3_7", "internalAddress": "2.7", "type": "HAE_METER_v3_7", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_7", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "771473.00"}, "dev_2.8": {"uuid": "29196c6f-6f89-444a-b17b-5a88f7608f4b", "name": "HAE_METER_v3_8", "internalAddress": "2.8", "type": "HAE_METER_v3_8", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_8", "CurrentHeatQuantity": "NaN", "CurrentHeatFlow": "NaN"}, "dev_3": {"uuid": "43faeb68-3887-4990-ae66-3448d6c66422", "name": "HAE_METER_v3", "internalAddress": "3", "type": "HAE_METER_v3", "supportsCrc": "1", "ccList": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "supportedCC": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName": "HAE_METER_v3", "CurrentSensorStatus": "UNKNOWN"}, "dev_3.1": {"uuid": "f732e653-e521-4ec0-875e-a6c878bdaeb0", "name": "HAE_METER_v3_1", "internalAddress": "3.1", "type": "HAE_METER_v3_1", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "CurrentGasFlow": "NaN", "CurrentGasQuantity": "NaN", "DeviceName": "HAE_METER_v3_1"}, "dev_3.2": {"uuid": "e6529cd9-fdc5-47e2-bcc9-b9e97db2d9f8", "name": "HAE_METER_v3_2", "internalAddress": "3.2", "type": "HAE_METER_v3_2", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_2", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_3.3": {"uuid": "9cbae94a-baf9-4d7b-a7d8-c4eabc9c9ff1", "name": "HAE_METER_v3_3", "internalAddress": "3.3", "type": "HAE_METER_v3_3", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "OPERATIONAL", "DeviceName": "HAE_METER_v3_3", "CurrentElectricityFlow": "2075.00", "CurrentElectricityQuantity": "516047.00"}, "dev_3.4": {"uuid": "da157604-4f1f-4045-a9b8-eb0624afcaae", "name": "HAE_METER_v3_4", "internalAddress": "3.4", "type": "HAE_METER_v3_4", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_4", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_3.5": {"uuid": "a2c94392-fbe9-4508-9deb-63a2f1ca857a", "name": "HAE_METER_v3_5", "internalAddress": "3.5", "type": "HAE_METER_v3_5", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_5", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_3.6": {"uuid": "83b54dcb-4f0e-40b4-a359-9430ecd7b274", "name": "HAE_METER_v3_6", "internalAddress": "3.6", "type": "HAE_METER_v3_6", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_6", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_3.7": {"uuid": "3f9b9186-ab0d-43f4-bc08-6507d1fd03f9", "name": "HAE_METER_v3_7", "internalAddress": "3.7", "type": "HAE_METER_v3_7", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_7", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_3.8": {"uuid": "ec315cdf-a322-4de8-85ea-4faedc634b3c", "name": "HAE_METER_v3_8", "internalAddress": "3.8", "type": "HAE_METER_v3_8", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_8", "CurrentHeatQuantity": "NaN", "CurrentHeatFlow": "NaN"}, "dev_4": {"uuid": "5c279747-354c-4581-8c7c-c4b30b8dcf1f", "name": "KoffieStekker", "internalAddress": "4", "type": "NAS_WR01Z", "supportsCrc": "0", "ccList": "5e 72 86 85 59 5a 73 70 25 27 71 32 20", "supportedCC": "5e 72 86 85 59 5a 73 70 25 27 71 32 20", "nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName": "KoffieStekker", "TargetStatus": "0", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "240.00", "CurrentState": "0"}}

**Comment by IgorYbema** [comment]
Owh jij hebt een andere situatie.
Je hebt een normale toon meetmodule voor het meten van de slimme meter (via P1) en een 2e normale meetmodule voor je zonoptoon (omdat die misschien verderop op een PV verdeler zit?). Even kijken of daar iets voor te verzinnen valt.

**Comment by mehmetakin1996** [comment]
> Owh jij hebt een andere situatie.
> 
> Je hebt een normale toon meetmodule voor het meten van de slimme meter (via P1) en een 2e normale meetmodule voor je zonoptoon (omdat die misschien verderop op een PV verdeler zit?). Even kijken of daar iets voor te verzinnen valt.

Jah dat klopt die zit boven in zolder

**Comment by mehmetakin1996** [comment]
Waar en hoe stel je dit in HA?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: IgorYbema ***@***.***>
Verzonden: Wednesday, June 22, 2022 5:21:23 PM
Aan: cyberjunky/home-assistant-toon_smartmeter ***@***.***>
CC: mehmetakin1996 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [cyberjunky/home-assistant-toon_smartmeter] Zon op Toon (#39)


Als ik het goed theoretisch bekijk zou het met de laatste update die hier staat moeten werken. Had je dat al getest?

**Comment by mehmetakin1996** [comment]
Hoi @IgorYbema en @cyberjunky 

Ik heb nu gezien dat ik waardes zie bij **Toon P1 Power Solar.**
Dus dit werkt! Prima! Alleen als ik dit via Energie wilt toevoegen staat deze Entiteit niet erbij dus dan kan ik die niet kiezen.

Waar kan dit aan liggen?
![image](https://user-images.githubusercontent.com/86535798/186860766-2c507906-cde6-4b4d-8665-467ee347c776.png)

**Comment by cyberjunky** [comment]
Can you try release 1.0.23?

**Comment by mehmetakin1996** [comment]
Ik heb hier nog de versie 1.0.13 in HACS 

> Can you try release 1.0.23?

**Comment by mehmetakin1996** [comment]
@cyberjunky ik zie het helaas nog steeds niet.
Toon P1 Power Solar.

**Comment by cyberjunky** [comment]
Die moeten we hebben dat is de tellerstand, moment..

**Comment by mehmetakin1996** [comment]
Die zie ik wel maar de Power Solar niet.
Moet ik die met CNT misschien toevoegen bij Teruglevering?

**Comment by cyberjunky** [comment]
Ja

**Comment by mehmetakin1996** [comment]
Misschien nog een aanpassing voor Toon P1 Power Solar ?

**Comment by cyberjunky** [comment]
Nee, dashboard werkt met KwH waardes, voeg Solar Cnt  toe en wacht een paar uur

**Comment by mehmetakin1996** [comment]
Solar Cnt heb ik nu toegevoegd bij Teruglevering. Maar bij Zonnepanelen heb ik niks daar moet ik toch de Toon P1 Power Solar toevoegen?

**Comment by cyberjunky** [comment]
Waarom voeg je Solar Cnt niet toe bij zonnepanelen?
Teruglevering is aan het net, dus je smartmeter.

**Comment by cyberjunky** [comment]
Ik heb het zo:
![image](https://user-images.githubusercontent.com/5447161/186888754-7623ddab-1212-41f3-b1cf-fc90e1a55445.png)

**Comment by mehmetakin1996** [comment]
![image](https://user-images.githubusercontent.com/86535798/186888832-78c4288a-70c4-47b0-9ce8-7f3d309af4c5.png)

**Comment by cyberjunky** [comment]
Die prod Cnt's moeten bij teruglevering.

**Comment by mehmetakin1996** [comment]
Is dit prima zo? 
![image](https://user-images.githubusercontent.com/86535798/186889152-bc13ff72-4079-4159-98dd-76d7c70e4058.png)

**Comment by cyberjunky** [comment]
Ja precies!

**Comment by cyberjunky** [comment]
Zou je die screenshot in het wit willen maken?
Dan zet ik die in de readme..

**Comment by mehmetakin1996** [comment]
![image](https://user-images.githubusercontent.com/86535798/186889484-7cdbd5a4-3a41-4183-aeab-93d4d2904084.png)
Alstuuu

**Comment by cyberjunky** [comment]
Top bedankt

**Comment by mehmetakin1996** [comment]
Wat is die CO2 voetafdruk?

**Comment by cyberjunky** [comment]
Dat laat wat info zien over Carbon uitstoot, adhv verbruik/teruglevering

**Comment by mehmetakin1996** [comment]
![image](https://user-images.githubusercontent.com/86535798/186890979-5b30bdde-57d5-40ba-9574-4ef553c7411c.png)

Zie jij ook een streepje?

**Comment by cyberjunky** [comment]
Ik zie dit, maar niet echt duidelijk hoe die gevevens tot stand komen, HA weet immers niet wat voor soort stroom je gebruikt.
![image](https://user-images.githubusercontent.com/5447161/186891426-ad92f89e-9bc4-423a-926d-147e0bc7986c.png)

**Comment by mehmetakin1996** [comment]
Jou zonne energie ziet eer ook heel anders uit.
Check mijn voorbeeld... Zijn mijn gegevens wel juist?

**Comment by cyberjunky** [comment]
Let niet op die waardes, mijn sensor blijft soms hangen, dan reboot ik hem weer en heb ik ineens 88 KwH  op 1 dag (van laatste weken, zojuist herstart)

**Comment by cyberjunky** [comment]
Stale ticket, reopen if needed.
