### ISSUE TITLE
Current gas uasage

### ISSUE THREAD

**Issue by ErnieB44** [cyberjunky/home-assistant-toon_smartmeter#4]
Hello,

First of all.. you did a great job creating this component!
I was wondering if it's possible to create a sensor which contains the current gas usage. Right now, i'm only able to use total gas usage or last hour gas usage.

Thanks.

**Comment by cyberjunky** [comment]
Smartmeters only track Gas usage once per hour. There is no more data available. I guess they have done this to save battery life (the gasmeter sensor is standalone)

**Comment by ErnieB44** [comment]
That makes sense.. if the meters only tracks gas once per hour than there's nothing this component can do about it. Will mark this issue as closed.
Thanks!
