### ISSUE TITLE
BREAKING CHANGE in Home Assistant 2021.12

### ISSUE THREAD

**Issue by bafplus** [cyberjunky/home-assistant-toon_smartmeter#42]
Wordt al maanden voor gewaarschuwd en is nu een BREAKING CHANGE in HA 2021.12:

Entity climate.toon_thermostat (<class 'custom_components.toon_climate.climate.ThermostatDevice'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by cyberjunky** [comment]
@bafplus This is fixed in Release 1.0.12 of home-assistant-toon_climate (not this repo) :-)
