### ISSUE TITLE
wat betekenen de sensoren? - what do the sensors mean?

### ISSUE THREAD

**Issue by jboesh** [cyberjunky/home-assistant-toon_smartmeter#46]
===dutch
Hi
( ik ga ervanuit dat je Nederlands spreekt, zo niet, heb ik de vertaling hieronder gezet)
Wil je misschien uitleggen wat de sensoren betekenen? om er een beter beeld van te krijgen.

Wat zijn bijvoorbeeld de verschillen tussen:
  - sensor.toon_p1_power_prod_low
  - sensor.toon_p1_power_prod_cnt_low
  - sensor.toon_p1_power_use_cnt_low

Wat betekent _prod_ en _cnt_ eigenlijk?

ik zie dat P1 Power Prod Low en PI Power Prod High geen data weergeeft, die staan op 0.00 Watt, weet jij wat daar de redenen voor zijn?

Alvast bedankt!!!

==English
could you explain what the sensors mean? to get a better idea of it!

for example, what are the differences between:
   - sensor.toon_p1_power_prod_low
   - sensor.toon_p1_power_prod_cnt_low
   - sensor.toon_p1_power_use_cnt_low

what does _prod_ and _cnt_ actually mean?

I see that P1 Power Prod Low and PI Power Prod High do not display data, they are at 0.00 Watt, do you know what the reasons are for that?

Thank you in advance!!!

**Comment by cyberjunky** [comment]
prod is productie (zonnepanelen die stroom opwekken)
cnt = counter = tellerstand
prod_low is realtime data voor laag tarief
prod_cnt_low is tellerstand productie/teruglevering laag tarief
