### ISSUE TITLE
P1 Heat

### ISSUE THREAD

**Issue by marcoheijkoop** [cyberjunky/home-assistant-toon_smartmeter#47]
Ik zie bij P1 Heat onbekend staan. Komt dat omdat de informatie niet uitgelezen kan worden? Ik zie die waardes namelijk wel in de Toon staan.

**Comment by cyberjunky** [comment]
P1 Heat is voor stadsverwarming of airco oid... heb het nog nooit gebruikt zien worden, wat zie je op je toon?

**Comment by marcoheijkoop** [comment]
Ik heb nu een Toon 2 en daar zie ik de warmte nog niet.

Op de Toon 1 zag ik Warmte en zag ik ook het verbruik

Met vriendelijke groet,

Marco Heijkoop
Mob: +31624096441


Op 18 jan. 2022 om 15:25 heeft Ron Klinkien ***@***.***> het volgende geschreven:

﻿
P1 Heat is voor stadsverwarming of airco oid... heb het nog nooit gebruikt zien worden, wat zie je op je toon?

**Comment by cyberjunky** [comment]
@marcoheijkoop laatste regel toevoegen aan je yaml log entries, dan restarten en zoeken in je home assistant log naar toon_smartmeter output
```
logger:
  default: info
  logs:
    custom_components.toon_smartmeter: debug
```

**Comment by cyberjunky** [comment]
Stale ticket, reopen if needed
