### ISSUE TITLE
Geen elektriciteit en gas verbruik bij Toon 2

### ISSUE THREAD

**Issue by P-Verbrugge** [cyberjunky/home-assistant-toon_smartmeter#48]
Gisteren heb ik mijn Toon vervangen voor een Toon 2. Beidde Toons heb ik geroot. Bij de oude Toon had ik geen problemen met uitlezen van de waarden. Bij de nieuwe Toon 2 krijg ik niets meer door. Ik kan wel de Toon 2 bedienen en van programma wisselen, etc. Ik zie ook de temperatuur ingesteld en huidige temperatuur, etc.

Alleen elektriciteit en gas verbruik sensoren blijven nu op 0 staan. Er komt niets terug, terwijl ik wel op de Toon 2 mijn verbruik vandaag voor gas, elektriciteit kan zien. De meters werken wel. De Toon 2 zit ook op hetzelfde IP adres als de oude Toon, om m'n config niet te hoeven wisselen. Het enige dat ik heb moeten aanpassen is de poort. Die stond op 10080 en heb ik op de standaard 80 moeten zetten.

Wat overigens aangepast is nu is de meter en de ketel module. Dit zijn nieuwste meter en ketel module. Deze zijn ook iets groter dan de oude met een status lampje er op.

Als ik inhoud van de Json (<ipadres>/hdrv_zwave?action=getDevices.json) opvraag krijg ik de volgende output (uids even vervangen):

> {
    "dev_settings_device": {
        "uuid": "xxxxx",
        "name": "settings_device",
        "internalAddress": "settings_device",
        "type": "settings_device"
    },
    "dev_2": {
        "uuid": "xxxxx",
        "name": "Meterkast",
        "internalAddress": "2",
        "type": "HAE_METER_v4",
        "supportsCrc": "1",
        "ccList": "xxxxx",
        "supportedCC": "xxxxx",
        "nodeFlags": [],
        "IsConnected": "1",
        "HealthValue": "10",
        "DeviceName": "Meterkast",
        "CurrentSensorStatus": "UNKNOWN"
    },
    "dev_2.1": {
        "uuid": "xxxxx",
        "name": "HAE_METER_v4_1",
        "internalAddress": "2.1",
        "type": "HAE_METER_v4_1",
        "supportsCrc": "0",
        "ccList": "5e 59 85 8e 3c 3d 3e",
        "supportedCC": "5e 59 85 8e 3c 3d 3e",
        "nodeFlags": [],
        "CurrentSensorStatus": "OPERATIONAL",
        "CurrentGasFlow": "4.00",
        "CurrentGasQuantity": "1742071.00",
        "DeviceName": "HAE_METER_v4_1"
    },
    "dev_2.2": {
        "uuid": "xxxxx",
        "name": "HAE_METER_v4_2",
        "internalAddress": "2.2",
        "type": "HAE_METER_v4_2",
        "supportsCrc": "0",
        "ccList": "5e 59 85 8e 3c 3d 3e",
        "supportedCC": "5e 59 85 8e 3c 3d 3e",
        "nodeFlags": [],
        "CurrentSensorStatus": "UNKNOWN",
        "DeviceName": "HAE_METER_v4_2",
        "CurrentElectricityFlow": "NaN",
        "CurrentElectricityQuantity": "NaN"
    },
    "dev_2.3": {
        "uuid": "xxxxx",
        "name": "HAE_METER_v4_3",
        "internalAddress": "2.3",
        "type": "HAE_METER_v4_3",
        "supportsCrc": "0",
        "ccList": "5e 59 85 8e 3c 3d 3e",
        "supportedCC": "5e 59 85 8e 3c 3d 3e",
        "nodeFlags": [],
        "CurrentSensorStatus": "UNKNOWN",
        "DeviceName": "HAE_METER_v4_3",
        "CurrentElectricityFlow": "NaN",
        "CurrentElectricityQuantity": "NaN"
    },
    "dev_2.4": {
        "uuid": "xxxxx",
        "name": "HAE_METER_v4_4",
        "internalAddress": "2.4",
        "type": "HAE_METER_v4_4",
        "supportsCrc": "0",
        "ccList": "5e 59 85 8e 3c 3d 3e",
        "supportedCC": "5e 59 85 8e 3c 3d 3e",
        "nodeFlags": [],
        "CurrentSensorStatus": "OPERATIONAL",
        "DeviceName": "HAE_METER_v4_4",
        "CurrentElectricityFlow": "0.00",
        "CurrentElectricityQuantity": "3563788.00"
    },
    "dev_2.5": {
        "uuid": "xxxxx",
        "name": "HAE_METER_v4_5",
        "internalAddress": "2.5",
        "type": "HAE_METER_v4_5",
        "supportsCrc": "0",
        "ccList": "5e 59 85 8e 3c 3d 3e",
        "supportedCC": "5e 59 85 8e 3c 3d 3e",
        "nodeFlags": [],
        "CurrentSensorStatus": "UNKNOWN",
        "DeviceName": "HAE_METER_v4_5",
        "CurrentElectricityFlow": "0.00",
        "CurrentElectricityQuantity": "4.00"
    },
    "dev_2.6": {
        "uuid": "xxxxx",
        "name": "HAE_METER_v4_6",
        "internalAddress": "2.6",
        "type": "HAE_METER_v4_6",
        "supportsCrc": "0",
        "ccList": "5e 59 85 8e 3c 3d 3e",
        "supportedCC": "5e 59 85 8e 3c 3d 3e",
        "nodeFlags": [],
        "CurrentSensorStatus": "UNKNOWN",
        "DeviceName": "HAE_METER_v4_6",
        "CurrentElectricityFlow": "381.00",
        "CurrentElectricityQuantity": "3336496.00"
    },
    "dev_2.7": {
        "uuid": "xxxxx",
        "name": "HAE_METER_v4_7",
        "internalAddress": "2.7",
        "type": "HAE_METER_v4_7",
        "supportsCrc": "0",
        "ccList": "5e 59 85 8e 3c 3d 3e",
        "supportedCC": "5e 59 85 8e 3c 3d 3e",
        "nodeFlags": [],
        "CurrentSensorStatus": "UNKNOWN",
        "DeviceName": "HAE_METER_v4_7",
        "CurrentElectricityFlow": "0.00",
        "CurrentElectricityQuantity": "3.00"
    },
    "dev_2.8": {
        "uuid": "xxxxx",
        "name": "HAE_METER_v4_8",
        "internalAddress": "2.8",
        "type": "HAE_METER_v4_8",
        "supportsCrc": "0",
        "ccList": "5e 59 85 8e 3c 3d 3e",
        "supportedCC": "5e 59 85 8e 3c 3d 3e",
        "nodeFlags": [],
        "CurrentSensorStatus": "UNKNOWN",
        "DeviceName": "HAE_METER_v4_8",
        "CurrentHeatQuantity": "NaN",
        "CurrentHeatFlow": "NaN"
    },
    "dev_2.9": {
        "uuid": "xxxxx",
        "name": "HAE_METER_v4_9",
        "internalAddress": "2.9",
        "type": "HAE_METER_v4_9",
        "supportsCrc": "0",
        "ccList": "5e 59 85 8e 3c 3d 3e",
        "supportedCC": "5e 59 85 8e 3c 3d 3e",
        "nodeFlags": [],
        "CurrentSensorStatus": "UNKNOWN",
        "DeviceName": "HAE_METER_v4_9",
        "CurrentWaterQuantity": "NaN",
        "CurrentWaterFlow": "NaN"
    }
}

Zit er een fout in mijn installatie of zit er iets in het script? Heb het add-on via HACS al opnieuw geïnstalleerd. Sensoren een keer allemaal verwijderd en opnieuw laten aanmaken na reboot. Maar geen resultaat zover.

Ik draai alles op HA 2022.2.9. Verder zie ik ook geen errors in de log. Heb de logging aangezet. Alles lijkt te functioneren, op het feit na dat de waarden op 0 blijven staan.

Edit: Link naar afbeelding van de toon met meters: https://www.dropbox.com/s/v2s1tx4x36kuoo7/Toon2.JPG?dl=0

**Comment by IgorYbema** [comment]
Ik heb een patch gemaakt in mijn repo. Je zou die kunnen testen. Als het goed is werkt dat:

https://github.com/IgorYbema/home-assistant-toon_smartmeter/commit/c4ac516f4c730462ba6c9b5278a0e543f6a2fc14

**Comment by P-Verbrugge** [comment]
> Ik heb een patch gemaakt in mijn repo. Je zou die kunnen testen. Als het goed is werkt dat:
> 
> [IgorYbema@c4ac516](https://github.com/IgorYbema/home-assistant-toon_smartmeter/commit/c4ac516f4c730462ba6c9b5278a0e543f6a2fc14)

Tof! Heb de code overgenomen en zie resultaat. Komt alleen nog niet overeen met wat ik op de meter zie. Dat probleem had ik eerder ook als ik halverwege de dag begon te meten. Benieuwd wat er morgen staat! 

Hartelijk dank!

**Comment by IgorYbema** [comment]
Eigenlijk moet het precies tonen wat je ook kan ophalen in die json file.
En dat moet weer overeenkomen met wat er op de Toon staat (Watt realtime)
Of bedoel je de kWh? Die telt eeuwig door.

**Comment by IgorYbema** [comment]
En? hoe is het vandaag?

**Comment by P-Verbrugge** [comment]
Ik heb dit in mijn config staan:

`
living_room_thermostat_daily_energy_high:
  source: sensor.toon_p1_power_use_cnt_high
  cycle: daily
`

Het lijkt er echter op dat ik, zoals je al eerder aanhaalde, toch het totaal binnen krijg. Het komt in ieder geval niet overeen met de 2kwh die op de toon staat. :-D

**Comment by IgorYbema** [comment]
Sowieso is het dan high + low die je moet optellen. Als ik cycle:daily goed begrijp zou hij dan vervolgens elke dag op 0 beginnen moeten en vanuit de source het verschil moeten rekenen. Maar ben zelf een HomeAss beginner :)
De data klopt nu vanuit de plugin. Nu is het aan jou om home assistant goed te zetten qua config (miscchien gebruik makende van de nieuwe energy map).

**Comment by P-Verbrugge** [comment]
Ik kijken of ik daar iets mee kan doen. Voorheen was de cycle daily genoeg. Wellicht dat daar recent iets in verandert is en niet gezien heb in de release notes.

**Comment by Smiggel** [comment]
Ik heb geen zonnepanelen.

Uiteindelijk is het gelukt door alle entiteiten die te maken hebben met de Toon te verwijderen. HA opnieuw starten en het energie dashboard aanzetten. Toen ging de berekening plots weer goed. 🤷‍♂️

Ook na de uitschakeling van het energie dashboard gaat het goed.

De Toon 2 is echt een verademing ten opzichte van de Toon 1. Reageert super goed. Geen vertragingen meer. 
Heb de mijne via Markplaats te pakken weten te krijgen voor een prima lange prijs.

**Comment by P-Verbrugge** [comment]
Ik heb geen zonnepanelen.

Uiteindelijk is het gelukt door alle entiteiten die te maken hebben met de Toon te verwijderen. HA opnieuw starten en het energie dashboard aanzetten. Toen ging de berekening plots weer goed. 🤷‍♂️

Ook na de uitschakeling van het energie dashboard gaat het goed.

De Toon 2 is echt een verademing ten opzichte van de Toon 1. Reageert super goed. Geen vertragingen meer. 
Heb de mijne via Markplaats te pakken weten te krijgen voor een prima lange prijs.
