### ISSUE TITLE
Graag de laatste P1 meter (V4) van Toon 2 toevoegen

### ISSUE THREAD

**Issue by rriempie** [cyberjunky/home-assistant-toon_smartmeter#49]
Hoi Cyberjunky,

Wil je de module bijwerken zodat ook de laatste versie P1 meter V4 kan worden uitgelezen?
Alvast bedankt!

**Comment by IgorYbema** [comment]
Zie ook https://github.com/cyberjunky/home-assistant-toon_smartmeter/issues/48 waar jij ook gepost hebt. Kan je deze sluiten?

**Comment by cyberjunky** [comment]
Ik heb geen Toon v2 om te testen, en zie zo 123 niet wat er gefixt moet worden, heb je toevallig een korte update/link naar exacte fix?

**Comment by cyberjunky** [comment]
Ik zie nu je repo staan, kun je een pull request openen?

**Comment by cyberjunky** [comment]
Is dit nog van toepassing?

**Comment by rriempie** [comment]
Nee hoor, het werkt nu naar behoren.

Mvg,

Ramon

**Comment by cyberjunky** [comment]
Thanks!
