### ISSUE TITLE
Update 1.0.24

### ISSUE THREAD

**Issue by Tazmanian79** [cyberjunky/home-assistant-toon_smartmeter#56]
Na installatie van 1.0.24 worden er geen meterstanden meer geregisteerd.
Na terugplaatsen van bestanden 1.0.23 werkt alles terug.

![update](https://user-images.githubusercontent.com/2421824/196892406-5cc7f877-f07d-4400-9bf0-cb1ad68d2e51.png)

**Comment by cyberjunky** [comment]
Vreemd, ik had het getest en bij werkt het ,zie je iets in de logfiles?
Alleen water werkt de rest niet meer? Dus dit is een Boxx?
![image](https://user-images.githubusercontent.com/5447161/196903751-29974a2a-8b14-4d5b-89d8-d4462dbe4ee3.png)

**Comment by Tazmanian79** [comment]
Omdat na de update er dan tijdelijk 0 stond overal heb ik nu in mijn energiedashboard totaal verkeerde waarden.
Tijdelijk 0 en dan terug aangepast naar de actuele waarden maar lijkt het alsof ik een gigantisch verbruik heb het laatste uur.  Dat is uiteraard niet correct.  Kan ik dit handmatig corrigeren?

![Schermafbeelding 2022-10-20 110841](https://user-images.githubusercontent.com/2421824/196906940-798e524d-995b-45f4-aa84-26abb21a44ad.png)

**Comment by cyberjunky** [comment]
Ik heb gestest met Toon 1 zonder water, kan het zijn dat je handmatig toegevoegde water sensors een conflict vormen met de sensoren die in de laatste versie zitten?

```
  - sensor.toon_p1_waterquantity
  - sensor.toon_p1_waterflow
```

Wellicht helpt dit je verder, als je een standaard SQLite database gebruikt
https://community.home-assistant.io/t/how-to-fix-statistics-data-e-g-energy-data/360966

**Comment by Tazmanian79** [comment]
Ik heb de verkeerde waarden kunnen aanpassen dankzij het aanpassen via statistieken in ontwikkelhulpmiddelen, dus dat staat allemaal terug goed.

Deze entiteiten zijn toegevoegd.  Maar is niet handmatig gebeurd, heb gewoon in de file gezet zoals het hoort en zijn dan automatisch toegevoegd.
- sensor.toon_p1_waterflow
- sensor.toon_p1_waterquantity

**Comment by cyberjunky** [comment]
Sorry voor het ongemakt, ik kan de Engie Boxx integratie hier niet testen helaas.
Je hebt niet toevallig een test HA instance om wat logfile output te genereren?

**Comment by cyberjunky** [comment]
Ik zal de code die je stuurde vergelijken

**Comment by Tazmanian79** [comment]
Nee helaas geen test instance hier.

Alles werkt nu terug dus ook de water module via de sensor.py dat ik zelf gemerged hebt van versie 1.0.23
lijkt erop dat er iets niet goed gaat ivm aanpassen van Nan naar 0 vermoed ik.

**Comment by cyberjunky** [comment]
Ja precies dat ben ik aan het terugdraaien, wellicht geeft de Boxx een ander bestands type/mime terug

**Comment by Tazmanian79** [comment]
Bij deze nog een kopie van mijn GetDevices.json
[getDevices.zip](https://github.com/cyberjunky/home-assistant-toon_smartmeter/files/9828440/getDevices.zip)

**Comment by cyberjunky** [comment]
Ik heb versie 1.0.25 uitgebracht, die is gelijk aan de code hierboven (zonder enkele comment regels) dus die zou moeten werken.
Ik weet eigenlijk niet meer wat er nu zo storend aan NaN waardes was, eigenlijk is dat precies waar het voor is...

**Comment by Tazmanian79** [comment]
1.0.25 geinstalleerd en alles blijft werken 👍

**Comment by cyberjunky** [comment]
Top, dank voor melden en testen!

**Comment by Wesley-Vos** [comment]
Allereerst, wat vervelend en gek dat het misging! De reden dat die NaN waardes vervangen moeten worden is omdat de Toon NaN teruggeeft voor afnemend en terugleverend vermogen van het tarief dat niet actief is totdat dat tarief weer actief wordt. Bijvoorbeeld, het afgenomen en teruggeleverd vermogen van hoog tarief blijven NaN na een herstart van de Toon in het weekend tot maandagochtend wanneer het hoge tarief weer gaat lopen. De afgenomen en teruggeleverd energie van het inactieve tarief worden wel netjes terug gegeven na een reboot.

Wanneer je in HA uitrekent wat het afgenomen of terugleverend vermogen is kan je hoog en laag tarief simpelweg optellen omdat die nooit tegelijk > 0 kunnnen zijn. Alleen, die berekening gaat mis is als een van beide NaN is. 

Nu zou je dit kunnen meenemen in de HA calculatie maar het zou mooier zijn om dit bij de bron op te lossen, namelijk de Toon die dan 0 moet geven. 'NaN' vermogen is ook een beetje gek want je weet dat het 0 moet zijn.

**Comment by cyberjunky** [comment]
Closing, stale ticket.
