### ISSUE TITLE
Watermeter

### ISSUE THREAD

**Issue by Tazmanian79** [cyberjunky/home-assistant-toon_smartmeter#60]
Het energydashboard kan nu ook het waterverbruik opvolgen.
Echter in kan de entiteit niet selecteren.  Enig idee wat er dient te gebeuren om de entiteit compatibel te maken voor het energy dashboard?

**Comment by cyberjunky** [comment]
@Tazmanian79 ik kan het snel toevoegen, maar heb geen water meter aan mijn toon, is de 'waterquantity' sensor een tellerstand die alleen omhoog loopt, en is de waarde in m3 ?

**Comment by Tazmanian79** [comment]
sensor.toon_p1_waterflow = huidige verbruik per liter per uur
sensor.toon_p1_waterquantity = oplopend verbruik m³

**Comment by cyberjunky** [comment]
@Tazmanian79 check version 1.0.29, thanks for reporting.

**Comment by Tazmanian79** [comment]
Heb versie 1.0.29 geinstalleerd, de registratie klopt maar de sensor.toon_p1_waterquantity = oplopend verbruik is toch in liter niet in m³.  Had deze statistieken nog niet echt goed bekeken, sorry daarvoor.

Dit moet aangepast worden want heb nu 28.000l verbruik per dag ;-)
