### ISSUE TITLE
Vraagje over de power prod sensoren

### ISSUE THREAD

**Issue by jboesh** [cyberjunky/home-assistant-toon_smartmeter#61]
He, even een snelle vraag. 
Deze sensoren geven data van de zonnepanelen opbrengst toch? Of is dit de opgewekte stroom die terug gaat naar het net? (Teruglevering) dus min je eigen verbruik?

  - sensor.toon_p1_power_prod_low
  - sensor.toon_p1_power_prod_high
  - sensor.toon_p1_power_prod_cnt_low
  - sensor.toon_p1_power_prod_cnt_high
 
Alvast bedankt

**Comment by cyberjunky** [comment]
@jboesh Ja Power Production is de stroom die je terug naar het net stuurt.
