### ISSUE TITLE
Minor issue Energy dashboard

### ISSUE THREAD

**Issue by Jopandrik** [cyberjunky/home-assistant-toon_smartmeter#62]
Hi,

I am using the last version of integration which is version 1.0.29.

Editing the Energy dashboard I get the following warning:

         Last reset missing
         The following entities have state class 'measurement' but 'last_reset' is missing:
          sensor.toon_gas_used_last_hour

Thank you for this Home-Assistant integration.

Regards, Harry

![2022-11-11 21_54_43-Settings – Home Assistant](https://user-images.githubusercontent.com/112260178/201429471-bc204f13-e5c7-4da0-901d-6388672ae0ae.png)

**Comment by cyberjunky** [comment]
Is this still an issue, I haven't seen it here?

**Comment by Jopandrik** [comment]
No, this problem was caused by myself, when trying to translate the various states to Dutch!
