### ISSUE TITLE
P1 Smartmeter unavailable / niet bereikbaar in Home Assistant 2023.1.7 docker.

### ISSUE THREAD

**Issue by MJPVDH** [cyberjunky/home-assistant-toon_smartmeter#67]
Sinds een tijdje is mijn P1 Smartmeter niet meer zichtbaar in Home Assistant.

![image](https://user-images.githubusercontent.com/48616802/215325910-86246357-6a51-4625-a41a-8000fb7e9173.png)

Terwijl Toon Thermostat (climate) het wel doet.

![image](https://user-images.githubusercontent.com/48616802/215325806-823e91c2-130b-42d3-a361-17da3f1d4997.png)

Ik gebruik HA in Docker:

Home Assistant 2023.1.7
Frontend-versie: 20230110.0 - latest

Wat kan het probleem zijn?

Dit staat in mijn config:

![image](https://user-images.githubusercontent.com/48616802/215326062-ceae14ae-264a-435f-8b63-4eb2895065c3.png)

**Comment by cyberjunky** [comment]
Nog even gekeken, maar draait hier gewoon nog prima op 2023.01.07
Check of IP adres nog klopt, en of je niet dubbele devices heb, als je zoekt onder ontwikkelhulmiddelen.

**Comment by cyberjunky** [comment]
Stale ticket, closing
