### ISSUE TITLE
when the communication is interrupted for short time with the Toon reading become NaN but never recover until restart HA

### ISSUE THREAD

**Issue by samimasad** [cyberjunky/home-assistant-toon_smartmeter#68]
if for whatever reason the communication is interrupted the Toon P1 readings all become NaN , however it never recover until you have a HA reboot , what is strange that Toon Gas reading do recover while the power doesnt

**Comment by cyberjunky** [comment]
I cannot think about a reason why this happens, they should recover. Is this still an issue?

**Comment by samimasad** [comment]
did not have connection again since then
