### ISSUE TITLE
sensor.toon_p1_power_use_cnt gives statistics_not_defined in HA

### ISSUE THREAD

**Issue by B4ttleduck** [cyberjunky/home-assistant-toon_smartmeter#71]
Upon setting the sensor.toon_p1_power_use_cnt  as Grid consumption source, I receive the error statistics_not_defined.
The use_cnt_low and use_cnt_high are working fine.

Below my Configuration.YAML

`# Toon intergration

sensor:
  - platform: toon_smartmeter
    host: IP.FROM.MY.TOON
    port: 80
    scan_interval: 10
    resources:
      - gasused
      - gasusedcnt
      - elecusageflowpulse
      - elecusagecntpulse
      - elecusageflowlow
      - elecusagecntlow
      - elecusageflowhigh
      - elecusagecnthigh
      - elecprodflowlow
      - elecprodcntlow
      - elecprodflowhigh
      - elecprodcnthigh
      - elecsolar
      - elecsolarcnt
      - heat
      - waterflow
      - waterquantity
      `

 Home Assistant 2023.2.5 Supervisor 2023.01.1 Operating System 9.5 Frontend 20230202.0 - latest

**Comment by cyberjunky** [comment]
`sensor.p1_power_use_cnt` is actually `sensor.power_use_cnt` (this is for pulse) I just renamed it in the code, it was a bug.
The P1 meteradapter doesn't publish a total use count for P1, only low and high

But you can create a template sensor for it, read here:
https://github.com/cyberjunky/home-assistant-toon_smartmeter/tree/master?tab=readme-ov-file#get-usage-of-your-house-disregarding-current-tarif
