### ISSUE TITLE
Feature request : optical sensor for electricity

### ISSUE THREAD

**Issue by mulleer** [cyberjunky/home-assistant-toon_smartmeter#77]
The current version provides the P1 sensors for electricity and the gas sensors. It would be nice to get it providing the electricity sensors based on  the analog (rotating disc) electricity meter too (the same way it currently works with the analog gas meter) .
https://manuals-backend.z-wave.info/make.php?lang=en&sku=6500-1400-6000&cert=ZC10-15040005
<img width="531" alt="Quby schéma infrastructure 02" src="https://github.com/cyberjunky/home-assistant-toon_smartmeter/assets/17429644/0e54cbbe-632a-4f2a-95c4-26e4b4f54110">

**Comment by cyberjunky** [comment]
Hi Eric @mulleer, first of all thank you for your kind donation via Paypal! If I understand your request correctly you want to count the disc rotation of the analog power meter, your Toon should also have a metersensor for this included, and if connected to the meteradapter your counts should already be available under this sensor, if not let me know and we can check how to debug it.
```  - sensor.toon_power_use_cnt```

**Comment by mulleer** [comment]
Hi,

You understand correctly.
My Toon shows correctly the data based on the disc rotation count  but on
https://github.com/cyberjunky/home-assistant-toon_smartmeter I don't see a
sensor for it and nothing is available in Home Assistant

Eric



[image: image.png]
[image: image.png]

[image: image.png]

**Comment by cyberjunky** [comment]
@mulleer You should see these sensors, they are the analog pulse ones:
```
 - elecusageflowpulse
 - elecusagecntpulse
```
Can you find those using a search in the development tool gui?

You can also browser with a browser to an address like this http://IP:PORT/hdrv_zwave?action=getDevices.json and paste the output here...
Port is mostly 80

**Comment by mulleer** [comment]
Thank you for your follow-up !
Here is what I get while browsing to my rooted Toon device (
http://IP:PORT/hdrv_zwave?action=getDevices.json
<http://ip:PORT/hdrv_zwave?action=getDevices.json> )


{"dev_settings_device": {"uuid": "40435d6f-4228-4862-bc40-906fdeebbb5b",
"name": "settings_device", "internalAddress": "settings_device", "type":
"settings_device"}, "dev_9": {"uuid":
"84c43bd6-ad77-4fbc-b834-f6bd84018d5b", "name": "HAE_METER_v4",
"internalAddress": "9", "type": "HAE_METER_v4", "supportsCrc": "1",
"ccList": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e",
"supportedCC": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e",
"nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName":
"HAE_METER_v4", "CurrentSensorStatus": "UNKNOWN"}, "dev_9.1": {"uuid":
"0be9e05b-6b06-4b8c-8834-146b463c939b", "name": "HAE_METER_v4_1",
"internalAddress": "9.1", "type": "HAE_METER_v4_1", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "OPERATIONAL", "CurrentGasFlow":
"0.00", "CurrentGasQuantity": "334460.00", "DeviceName": "HAE_METER_v4_1"},
"dev_9.2": {"uuid": "b72fae43-1094-47ae-a6b7-f943dd0b25b4", "name":
"HAE_METER_v4_2", "internalAddress": "9.2", "type": "HAE_METER_v4_2",
"supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59
85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "OPERATIONAL",
"DeviceName": "HAE_METER_v4_2", "CurrentElectricityFlow": "1472.00",
"CurrentElectricityQuantity": "4073531.00"}, "dev_9.3": {"uuid":
"9eaae0a5-8027-4236-b202-24788df30508", "name": "HAE_METER_v4_3",
"internalAddress": "9.3", "type": "HAE_METER_v4_3", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_3", "CurrentElectricityFlow": "NaN",
"CurrentElectricityQuantity": "NaN"}, "dev_9.4": {"uuid":
"2526a60d-4f42-428d-9607-d2545414f72f", "name": "HAE_METER_v4_4",
"internalAddress": "9.4", "type": "HAE_METER_v4_4", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_4", "CurrentElectricityFlow": "NaN",
"CurrentElectricityQuantity": "NaN"}, "dev_9.5": {"uuid":
"29c4f1f1-5d03-47f8-adb6-ccd320830f59", "name": "HAE_METER_v4_5",
"internalAddress": "9.5", "type": "HAE_METER_v4_5", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_5", "CurrentElectricityFlow": "NaN",
"CurrentElectricityQuantity": "NaN"}, "dev_9.6": {"uuid":
"cc0f37fe-ff5b-495c-87b5-9ed5d193dd20", "name": "HAE_METER_v4_6",
"internalAddress": "9.6", "type": "HAE_METER_v4_6", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_6", "CurrentElectricityFlow": "NaN",
"CurrentElectricityQuantity": "NaN"}, "dev_9.7": {"uuid":
"2eeb004c-5473-4a84-a786-a4f93ac66dcc", "name": "HAE_METER_v4_7",
"internalAddress": "9.7", "type": "HAE_METER_v4_7", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_7", "CurrentElectricityFlow": "NaN",
"CurrentElectricityQuantity": "NaN"}, "dev_9.8": {"uuid":
"7047d58b-72bf-4985-83d7-813a6a02a949", "name": "HAE_METER_v4_8",
"internalAddress": "9.8", "type": "HAE_METER_v4_8", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_8", "CurrentHeatQuantity": "NaN", "CurrentHeatFlow": "NaN"},
"dev_9.9": {"uuid": "a5c2e1a3-84ae-472e-a1d9-f6a9ca6012b7", "name":
"HAE_METER_v4_9", "internalAddress": "9.9", "type": "HAE_METER_v4_9",
"supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59
85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN",
"DeviceName": "HAE_METER_v4_9", "CurrentWaterQuantity": "NaN",
"CurrentWaterFlow": "NaN"}, "dev_10": {"uuid":
"ed893067-1544-42aa-a8df-57c402fc8195", "name": "HAE_METER_v4",
"internalAddress": "10", "type": "HAE_METER_v4", "supportsCrc": "1",
"ccList": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e",
"supportedCC": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e",
"nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName":
"HAE_METER_v4", "CurrentSensorStatus": "UNKNOWN"}, "dev_10.1": {"uuid":
"68e28430-ef74-43c0-b335-bead0d308679", "name": "HAE_METER_v4_1",
"internalAddress": "10.1", "type": "HAE_METER_v4_1", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "CurrentGasFlow": "NaN",
"CurrentGasQuantity": "NaN", "DeviceName": "HAE_METER_v4_1"}, "dev_10.2":
{"uuid": "e04f8128-59ff-44f7-89ee-7b6240fc86f8", "name": "HAE_METER_v4_2",
"internalAddress": "10.2", "type": "HAE_METER_v4_2", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_2", "CurrentElectricityFlow": "NaN",
"CurrentElectricityQuantity": "NaN"}, "dev_10.3": {"uuid":
"5f0ebf8f-9824-4e9b-b1f7-88fc401fcad0", "name": "HAE_METER_v4_3",
"internalAddress": "10.3", "type": "HAE_METER_v4_3", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_3", "CurrentElectricityFlow": "NaN",
"CurrentElectricityQuantity": "NaN"}, "dev_10.4": {"uuid":
"f2f83f3c-f425-4b39-b5db-3b0f5ad3b69a", "name": "HAE_METER_v4_4",
"internalAddress": "10.4", "type": "HAE_METER_v4_4", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_4", "CurrentElectricityFlow": "NaN",
"CurrentElectricityQuantity": "NaN"}, "dev_10.5": {"uuid":
"198d2858-dfe9-44c8-8456-fd327b9f283b", "name": "HAE_METER_v4_5",
"internalAddress": "10.5", "type": "HAE_METER_v4_5", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_5", "CurrentElectricityFlow": "NaN",
"CurrentElectricityQuantity": "NaN"}, "dev_10.6": {"uuid":
"c3d67f6f-a7d3-431e-97ab-79b3b35d5c43", "name": "HAE_METER_v4_6",
"internalAddress": "10.6", "type": "HAE_METER_v4_6", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_6", "CurrentElectricityFlow": "NaN",
"CurrentElectricityQuantity": "NaN"}, "dev_10.7": {"uuid":
"0cafc465-6985-4498-8b52-4e141c88b7c6", "name": "HAE_METER_v4_7",
"internalAddress": "10.7", "type": "HAE_METER_v4_7", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_7", "CurrentElectricityFlow": "NaN",
"CurrentElectricityQuantity": "NaN"}, "dev_10.8": {"uuid":
"64c1a738-a590-4276-9e62-4b33e4a23bfc", "name": "HAE_METER_v4_8",
"internalAddress": "10.8", "type": "HAE_METER_v4_8", "supportsCrc": "0",
"ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e",
"nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":
"HAE_METER_v4_8", "CurrentHeatQuantity": "NaN", "CurrentHeatFlow": "NaN"},
"dev_10.9": {"uuid": "93c46cb0-9c88-448e-9bf1-1b42dbad9792", "name":
"HAE_METER_v4_9", "internalAddress": "10.9", "type": "HAE_METER_v4_9",
"supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59
85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "OPERATIONAL",
"DeviceName": "HAE_METER_v4_9", "CurrentWaterQuantity": "55705.00",
"CurrentWaterFlow": "0.00"}}

**Comment by cyberjunky** [comment]
Thanks, I think I found the issue, give me some time to fix it...

**Comment by cyberjunky** [comment]
I fixed it in version 1.0.33

**Comment by mulleer** [comment]
Great !
Thank you very much !!!

Eric

[image: image.png]
