### ISSUE TITLE
Waardes onbekend Toon Smart Meter

### ISSUE THREAD

**Issue by mehmetakin1996** [cyberjunky/home-assistant-toon_smartmeter#78]
Hoi! @cyberjunky 

Na de laatste update zie ik mijn waardes niet meer.
Werkte voorheen wel. Ik heb de versie 1.0.33

![image](https://github.com/cyberjunky/home-assistant-toon_smartmeter/assets/86535798/b3e398e9-44a4-4e4b-bf93-25791dc352a5)

**Comment by cyberjunky** [comment]
@mehmetakin1996 Arg maybe a bug sneaked in, can you post the output of this?

Browse with a browser to an address like this http://IP:PORT/hdrv_zwave?action=getDevices.json and paste the output here...
Ip is address of your Toon, Port is 80 most of the time.

**Comment by cyberjunky** [comment]
Can you try 1.0.34, found out not all sensors has the expected operational status I was checking for.

**Comment by Sethenor** [comment]
1.0.34 fixed it for me!

**Comment by mehmetakin1996** [comment]
I cant see the update?

**Comment by cyberjunky** [comment]
It shows up automatically in HACS.
Otherwise open the integration in HACS, and click the three dots and then update information.

**Comment by CorstianB** [comment]
I’ve the same issue. Updating to 1.0.34 did not help

**Comment by cyberjunky** [comment]
Did you restart? I see bo reason why that version shouldn't work.

**Comment by cyberjunky** [comment]
@CorstianB if you still have this issue, can you do the following to give me more info to work with?

Browse with a browser to an address like this http://ip:PORT/hdrv_zwave?action=getDevices.json and paste the output here...
Ip is address of your Toon, Port is 80 most of the time.

**Comment by mehmetakin1996** [comment]
Its works for me!

**Comment by CorstianB** [comment]
> @CorstianB if you still have this issue, can you do the following to give me more info to work with?
> 
> Browse with a browser to an address like this http://ip:PORT/hdrv_zwave?action=getDevices.json and paste the output here... Ip is address of your Toon, Port is 80 most of the time.

I fixed the issue. I virtualized my pfsense router a few days ago. yesterday the toon restarted due to a change in the certificates. after the restart it got a different ip. I recreated the dhcp reservation and restarted the toon. after that everything started working again.

**Comment by mehmetakin1996** [comment]
Hi @cyberjunky 

Ik heb gemerkt dat ik de Power Use High waarde niet zie in mijn HA.

sensor toon_smartmeter:
  - platform: toon_smartmeter
    host: 192.168......
    port: 80
    scan_interval: 10
    resources:
       - gasused
       - gasusedcnt
       - elecusageflowpulse
       - elecusagecntpulse
       - elecusageflowlow
       - elecusagecntlow
       - elecusageflowhigh
       - elecusagecnthigh
       - elecprodflowlow
       - elecprodcntlow
       - elecprodflowhigh
       - elecprodcnthigh
       - elecsolar
       - elecsolarcnt
       - heat
       

![image](https://github.com/cyberjunky/home-assistant-toon_smartmeter/assets/86535798/bdbcfd59-d8ab-42dd-a62e-a8873dcfaca5)

**Comment by cyberjunky** [comment]
@mehmetakin1996 Can you do this: browse with a browser to an address like this http://ip:PORT/hdrv_zwave?action=getDevices.json and paste the output here... Ip is address of your Toon, Port is 80 most of the time.

**Comment by mehmetakin1996** [comment]
> @mehmetakin1996 Can you do this: browse with a browser to an address like this http://ip:PORT/hdrv_zwave?action=getDevices.json and paste the output here... Ip is address of your Toon, Port is 80 most of the time.

Check! This one.

{"dev_settings_device": {"uuid": "ef7ca589-1c0a-4553-a19a-f96beafee75a", "name": "settings_device", "internalAddress": "settings_device", "type": "settings_device"}, "dev_2": {"uuid": "687aacff-078c-4866-806a-94408595aa70", "name": "HAE_METER_v3", "internalAddress": "2", "type": "HAE_METER_v3", "supportsCrc": "1", "ccList": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "supportedCC": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName": "HAE_METER_v3", "CurrentSensorStatus": "UNKNOWN"}, "dev_2.1": {"uuid": "fe97aea5-3b90-4e54-a5f6-793e2221eaf4", "name": "HAE_METER_v3_1", "internalAddress": "2.1", "type": "HAE_METER_v3_1", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "WARNING", "CurrentGasFlow": "4.00", "CurrentGasQuantity": "3421150.00", "DeviceName": "HAE_METER_v3_1"}, "dev_2.2": {"uuid": "98f918e9-9511-4ac2-9af7-958081a35ea6", "name": "HAE_METER_v3_2", "internalAddress": "2.2", "type": "HAE_METER_v3_2", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_2", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_2.3": {"uuid": "7162c8d2-3b0a-4271-b44c-dd7353cce730", "name": "HAE_METER_v3_3", "internalAddress": "2.3", "type": "HAE_METER_v3_3", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_3", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_2.4": {"uuid": "3e3d011a-e82f-4f21-9658-8a574d4b2a54", "name": "HAE_METER_v3_4", "internalAddress": "2.4", "type": "HAE_METER_v3_4", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "WARNING", "DeviceName": "HAE_METER_v3_4", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "7647631.00"}, "dev_2.5": {"uuid": "183e9d51-248d-4cd1-a507-4816f9bd5deb", "name": "HAE_METER_v3_5", "internalAddress": "2.5", "type": "HAE_METER_v3_5", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_5", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "3472460.00"}, "dev_2.6": {"uuid": "610c0238-8b84-489c-bda6-21e3e08ed9e4", "name": "HAE_METER_v3_6", "internalAddress": "2.6", "type": "HAE_METER_v3_6", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_6", "CurrentElectricityFlow": "272.00", "CurrentElectricityQuantity": "9039041.00"}, "dev_2.7": {"uuid": "60fdc89b-40f9-488a-85ed-3fb0d36061f4", "name": "HAE_METER_v3_7", "internalAddress": "2.7", "type": "HAE_METER_v3_7", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_7", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "1503749.00"}, "dev_2.8": {"uuid": "29196c6f-6f89-444a-b17b-5a88f7608f4b", "name": "HAE_METER_v3_8", "internalAddress": "2.8", "type": "HAE_METER_v3_8", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_8", "CurrentHeatQuantity": "NaN", "CurrentHeatFlow": "NaN"}, "dev_3": {"uuid": "43faeb68-3887-4990-ae66-3448d6c66422", "name": "HAE_METER_v3", "internalAddress": "3", "type": "HAE_METER_v3", "supportsCrc": "1", "ccList": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "supportedCC": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName": "HAE_METER_v3", "CurrentSensorStatus": "UNKNOWN"}, "dev_3.1": {"uuid": "f732e653-e521-4ec0-875e-a6c878bdaeb0", "name": "HAE_METER_v3_1", "internalAddress": "3.1", "type": "HAE_METER_v3_1", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "CurrentGasFlow": "NaN", "CurrentGasQuantity": "NaN", "DeviceName": "HAE_METER_v3_1"}, "dev_3.2": {"uuid": "e6529cd9-fdc5-47e2-bcc9-b9e97db2d9f8", "name": "HAE_METER_v3_2", "internalAddress": "3.2", "type": "HAE_METER_v3_2", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_2", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_3.3": {"uuid": "9cbae94a-baf9-4d7b-a7d8-c4eabc9c9ff1", "name": "HAE_METER_v3_3", "internalAddress": "3.3", "type": "HAE_METER_v3_3", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "OPERATIONAL", "DeviceName": "HAE_METER_v3_3", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "2873634.00"}, "dev_3.4": {"uuid": "da157604-4f1f-4045-a9b8-eb0624afcaae", "name": "HAE_METER_v3_4", "internalAddress": "3.4", "type": "HAE_METER_v3_4", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_4", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_3.5": {"uuid": "a2c94392-fbe9-4508-9deb-63a2f1ca857a", "name": "HAE_METER_v3_5", "internalAddress": "3.5", "type": "HAE_METER_v3_5", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_5", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_3.6": {"uuid": "83b54dcb-4f0e-40b4-a359-9430ecd7b274", "name": "HAE_METER_v3_6", "internalAddress": "3.6", "type": "HAE_METER_v3_6", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_6", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_3.7": {"uuid": "3f9b9186-ab0d-43f4-bc08-6507d1fd03f9", "name": "HAE_METER_v3_7", "internalAddress": "3.7", "type": "HAE_METER_v3_7", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_7", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_3.8": {"uuid": "ec315cdf-a322-4de8-85ea-4faedc634b3c", "name": "HAE_METER_v3_8", "internalAddress": "3.8", "type": "HAE_METER_v3_8", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_8", "CurrentHeatQuantity": "NaN", "CurrentHeatFlow": "NaN"}, "dev_4": {"uuid": "5c279747-354c-4581-8c7c-c4b30b8dcf1f", "name": "KoffieStekker", "internalAddress": "4", "type": "NAS_WR01Z", "supportsCrc": "0", "ccList": "5e 72 86 85 59 5a 73 70 25 27 71 32 20", "supportedCC": "5e 72 86 85 59 5a 73 70 25 27 71 32 20", "nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName": "KoffieStekker", "TargetStatus": "0", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "2410.00", "CurrentState": "0"}}

**Comment by cyberjunky** [comment]
Great, will have a look!

**Comment by cyberjunky** [comment]
I inserted 110 as value for Use High in your data, and I have the sensor (there seem to be abug in where Solar is the same as Use High though, but I have to look into that later.

But your device is completely missing, so I think there may be a duplicate or stray one which doesn't have the standard name, and this is missing from your card (or you have added it wrongly/or not at all.

Can you search for inside Development Tools/Statusses and search for 'use high' do you see multiple, or some with a _1 in the name? 
![image](https://github.com/cyberjunky/home-assistant-toon_smartmeter/assets/5447161/8460eea4-3cfd-4059-89ff-abc5de7229f9)

**Comment by mehmetakin1996** [comment]
Lijkt weer te werken. Alleen bij Energie Dashboard kan ik geen entiteiten toevoegen is niet beschikbaar.

![image](https://github.com/cyberjunky/home-assistant-toon_smartmeter/assets/86535798/320e1061-e61d-47ee-88a3-2cc1a1206e2e)

**Comment by mo-harry** [comment]
> I inserted 110 as value for Use High in your data, and I have the sensor (there seem to be abug in where Solar is the same as Use High though, but I have to look into that later.
> 
> But your device is completely missing, so I think there may be a duplicate or stray one which doesn't have the standard name, and this is missing from your card (or you have added it wrongly/or not at all.
> 
> Can you search for inside Development Tools/Statusses and search for 'use high' do you see multiple, or some with a _1 in the name? ![image](https://private-user-images.githubusercontent.com/5447161/293500495-8460eea4-3cfd-4059-89ff-abc5de7229f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTM4NTcsIm5iZiI6MTcwNDExMzU1NywicGF0aCI6Ii81NDQ3MTYxLzI5MzUwMDQ5NS04NDYwZWVhNC0zY2ZkLTQwNTktODlmZi1hYmM1ZGU3MjI5ZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDFUMTI1MjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjgxZmJlMzgxNWMwNmFlMzM1YjA5NWI1MTdlN2M0Y2M2MzIyMTQ5Njc3YjkzMjVkODNjZGU0NjBmZTBlMWQ5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TX2n2f5-P6miHy7C4rrlRmiZMUBQv5BRPjFM-u3SE90)

Not sure if the issue is solved or that the underlying cause was concluded?

I updated the integration a few times the last days and remember one of the release notes said: "renamed P1..." to something else. And that would be the problem in my case I assume? Because I do have duplicates now... How can I clean up and keep the original (and new) data?

**Comment by cyberjunky** [comment]
> Lijkt weer te werken. Alleen bij Energie Dashboard kan ik geen entiteiten toevoegen is niet beschikbaar.
> 

p1_power_use and p1_power_cnt where renamed some versions ago to power_use and power_cnt, since there are not P1 sensors, but the pulse sensors from Toon (the cables with the small led boxes attached) 

So if you really use them both P1, and the pulses sensors (not sure if this is possible) you need to select the power_use and power_use_cnt instead, if you are on P1 smartmeter mode only, look for p1_power_use_cnt_high and p1_power_use_cnt_low and select those

**Comment by cyberjunky** [comment]
> I updated the integration a few times the last days and remember one of the release notes said: "renamed P1..." to something else. And that would be the problem in my case I assume? Because I do have duplicates now... How can I clean up and keep the original (and new) data?

If you use the pulse counter sensors you can have dupes yes, I renamed them by removing the _p1 from the name.
You can go to settings, devices, an then entities, and remove the non working/old ones (they have a red shield behind them), check the new name and use those instead in your scripts, automation and energy dashboard.

**Comment by mo-harry** [comment]
> > I updated the integration a few times the last days and remember one of the release notes said: "renamed P1..." to something else. And that would be the problem in my case I assume? Because I do have duplicates now... How can I clean up and keep the original (and new) data?
> 
> If you use the pulse counter sensors you can have dupes yes, I renamed them by removing the _p1 from the name. You can go to settings, devices, an then entities, and remove the non working/old ones (they have a red shield behind them), check the new name and use those instead in your scripts, automation and energy dashboard.

By doing this, will i keep or lose my old energy data?

**Comment by cyberjunky** [comment]
> > > I updated the integration a few times the last days and remember one of the release notes said: "renamed P1..." to something else. And that would be the problem in my case I assume? Because I do have duplicates now... How can I clean up and keep the original (and new) data?
> > 
> > 
> > If you use the pulse counter sensors you can have dupes yes, I renamed them by removing the _p1 from the name. You can go to settings, devices, an then entities, and remove the non working/old ones (they have a red shield behind them), check the new name and use those instead in your scripts, automation and energy dashboard.
> 
> By doing this, will i keep or lose my old energy data?

Oh, I'm not sure, better have a backup and check first, maybe there is a way to rename them somehow, maybe google/ha forum

**Comment by cyberjunky** [comment]
> > > > I updated the integration a few times the last days and remember one of the release notes said: "renamed P1..." to something else. And that would be the problem in my case I assume? Because I do have duplicates now... How can I clean up and keep the original (and new) data?
> > > 
> > > 
> > > If you use the pulse counter sensors you can have dupes yes, I renamed them by removing the _p1 from the name. You can go to settings, devices, an then entities, and remove the non working/old ones (they have a red shield behind them), check the new name and use those instead in your scripts, automation and energy dashboard.
> > 
> > 
> > By doing this, will i keep or lose my old energy data?
> 
> Oh, I'm not sure, better have a backup and check first, maybe there is a way to rename them somehow, maybe google/ha forum
@mo-harry 

Maybe this will work:

- make a full backup
- disable smartmeter integration (comment config)
- restart
- remove device sensor.toon_power_use and  sensor.toon_power_use_cnt
- rename  sensor.toon_p1_power_use to sensor.toon_power_use (using clogwheel in device entitiy-id)
- same for _cnt device
- enable integration in code
- restart

**Comment by mo-harry** [comment]
> 
> Maybe this will work:
> 
> * make a full backup
> * disable smartmeter integration (comment config)
> * restart
> * remove device sensor.toon_power_use and  sensor.toon_power_use_cnt
> * rename  sensor.toon_p1_power_use to sensor.toon_power_use (using clogwheel in device entitiy-id)
> * same for _cnt device
> * enable integration in code
> * restart

Thanks. Those steps really helped. I ended up doing:
* make a full backup
* disable smartmeter integration (comment config)
* restart
* **removed all entities related to _toon_smartmeter_**
* enable integration in code
* restart

Ended up missing a few hours (that were registered under the entities that were ending with _2). I'll take that loss..

**Comment by mehmetakin1996** [comment]
Hi @cyberjunky,

Bij me broer werkt het nu opeens ook niet meer.
Zie onderstaande logs:

{"dev_2": {"uuid": "30f597b0-a8b9-4dd8-b558-7677d4187f05", "name": "HAE_METER_v3", "internalAddress": "2", "type": "HAE_METER_v3", "supportsCrc": "1", "ccList": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "supportedCC": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName": "HAE_METER_v3", "CurrentSensorStatus": "UNKNOWN"}, "dev_2.1": {"uuid": "38daf95c-109c-4d79-9f25-7cf7d9f71413", "name": "HAE_METER_v3_1", "internalAddress": "2.1", "type": "HAE_METER_v3_1", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "WARNING", "CurrentGasFlow": "2.00", "CurrentGasQuantity": "6454749.00", "DeviceName": "HAE_METER_v3_1"}, "dev_2.2": {"uuid": "d620326a-509f-4f00-9b6a-1f89ec6ac997", "name": "HAE_METER_v3_2", "internalAddress": "2.2", "type": "HAE_METER_v3_2", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_2", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_2.3": {"uuid": "a947a105-1b30-4a8b-a56f-72b360ecfdb6", "name": "HAE_METER_v3_3", "internalAddress": "2.3", "type": "HAE_METER_v3_3", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_3", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_2.4": {"uuid": "aeb1b0c4-a3d4-499e-9d2a-46b99bb2f44a", "name": "HAE_METER_v3_4", "internalAddress": "2.4", "type": "HAE_METER_v3_4", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "WARNING", "DeviceName": "HAE_METER_v3_4", "CurrentElectricityFlow": "359.00", "CurrentElectricityQuantity": "9791276.00"}, "dev_2.5": {"uuid": "56bc7e78-401c-4bff-9556-9d9ec2ccf65d", "name": "HAE_METER_v3_5", "internalAddress": "2.5", "type": "HAE_METER_v3_5", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_5", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "0.00"}, "dev_2.6": {"uuid": "a0b4dc12-79f6-41ca-a14b-564ba20433f1", "name": "HAE_METER_v3_6", "internalAddress": "2.6", "type": "HAE_METER_v3_6", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_6", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "9859620.00"}, "dev_2.7": {"uuid": "956dcc3a-85df-40d0-a9e8-8556097284f9", "name": "HAE_METER_v3_7", "internalAddress": "2.7", "type": "HAE_METER_v3_7", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":

**Comment by cyberjunky** [comment]
Er ontbreekt een stuk, kun je copy/pasten tot de laatste } ?
Maar wat werkt er precies niet? En wat voor devices zie je daar als je in de ontwikkelhulp.statussen naar 'toon' zoekt?

**Comment by mehmetakin1996** [comment]
> Er ontbreekt een stuk, kun je copy/pasten tot de laatste } ?
> 
> Maar wat werkt er precies niet? En wat voor devices zie je daar als je in de ontwikkelhulp.statussen naar 'toon' zoekt?

@cyberjunky bij deze

![image](https://github.com/cyberjunky/home-assistant-toon_smartmeter/assets/86535798/d5ab7f5d-c022-48fa-b90b-7ebbba9ed62a)

{"dev_2": {"uuid": "30f597b0-a8b9-4dd8-b558-7677d4187f05", "name": "HAE_METER_v3", "internalAddress": "2", "type": "HAE_METER_v3", "supportsCrc": "1", "ccList": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "supportedCC": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName": "HAE_METER_v3", "CurrentSensorStatus": "UNKNOWN"}, "dev_2.1": {"uuid": "38daf95c-109c-4d79-9f25-7cf7d9f71413", "name": "HAE_METER_v3_1", "internalAddress": "2.1", "type": "HAE_METER_v3_1", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "WARNING", "CurrentGasFlow": "2.00", "CurrentGasQuantity": "6454749.00", "DeviceName": "HAE_METER_v3_1"}, "dev_2.2": {"uuid": "d620326a-509f-4f00-9b6a-1f89ec6ac997", "name": "HAE_METER_v3_2", "internalAddress": "2.2", "type": "HAE_METER_v3_2", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_2", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_2.3": {"uuid": "a947a105-1b30-4a8b-a56f-72b360ecfdb6", "name": "HAE_METER_v3_3", "internalAddress": "2.3", "type": "HAE_METER_v3_3", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_3", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_2.4": {"uuid": "aeb1b0c4-a3d4-499e-9d2a-46b99bb2f44a", "name": "HAE_METER_v3_4", "internalAddress": "2.4", "type": "HAE_METER_v3_4", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "WARNING", "DeviceName": "HAE_METER_v3_4", "CurrentElectricityFlow": "359.00", "CurrentElectricityQuantity": "9791276.00"}, "dev_2.5": {"uuid": "56bc7e78-401c-4bff-9556-9d9ec2ccf65d", "name": "HAE_METER_v3_5", "internalAddress": "2.5", "type": "HAE_METER_v3_5", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_5", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "0.00"}, "dev_2.6": {"uuid": "a0b4dc12-79f6-41ca-a14b-564ba20433f1", "name": "HAE_METER_v3_6", "internalAddress": "2.6", "type": "HAE_METER_v3_6", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v3_6", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "9859620.00"}, "dev_2.7": {"uuid": "956dcc3a-85df-40d0-a9e8-8556097284f9", "name": "HAE_METER_v3_7", "internalAddress": "2.7", "type": "HAE_METER_v3_7", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName":

**Comment by cyberjunky** [comment]
@mehmetakin1996 zie hier en er onder...

https://github.com/cyberjunky/home-assistant-toon_smartmeter/issues/78#issuecomment-1873339616
