### ISSUE TITLE
Nieuwere versies na 1.0.34 bevatten mogelijk een bug?

### ISSUE THREAD

**Issue by Jopandrik** [cyberjunky/home-assistant-toon_smartmeter#79]
Hoi @cyberjunky Ron,

Ik heb mogelijk een probleem ontdekt m.b.t. de nieuwe versie van smartmeter.
Ik heb meerdere Home Assistant instanties en op eentje heb ik recentelijk de nieuwe versie geïnstalleerd en oonmiddelijk daarna konden de sensors van de toon niet meer uitgelezen worden, terwijl ik op hetzelfde systeem wel de betreffende sensors uit kon lezen via de browser met:

 [``](http://192.168.2.238/hdrv_zwave?action=getDevices.json)

Op een ander systeem met versie 1.0.34 werkt alles naar behoren. Alleen op het systeem met 1.0.36 heb ik problemen.

Ik heb daarom de 1.0.36 bestanden in de folder /config/custom_components/toon_smartmeter overschreven met die van 1.0.34 en na een reboot werkte alles weer.

Vandaag heb ik handmatig weer de bestanden van 1.0.36 geïnstalleerd en is het probleem weer terug!
Ik heb al aan het configuration.yaml bestand het  volgende toiegevoegd:

**logger:
  default: info
  logs:
    custom_components.toon_smartmeter: debug**

Ik zie echter niks in de log verschijnen!

Dit is wat ik krijg te zien:
 
![image](https://github.com/cyberjunky/home-assistant-toon_smartmeter/assets/112260178/ab261702-3cc4-48bc-a4e1-633252325867)

Kun jij me verder helpen om dit probleem te tackelen? Tips zijn welkom.

Met vrindelijke groet, Jopandrik

P.S. Ik gebruik Home Assistant 2024.1

**Comment by Jopandrik** [comment]
Ik heb de 1.0.34 versie terug gezet en krijg het gewenste resultaat te zien:

![image](https://github.com/cyberjunky/home-assistant-toon_smartmeter/assets/112260178/0b295fa7-8af5-4ba8-b336-e2adeb9d4b9a)

**Comment by cyberjunky** [comment]
@Jopandrik hallo, je zou toch eigenlijk wel iets in de logfiles moeten zien. Kun je anders eens log debug aanzetten, zie onderaan de documentatie. Ik kijk anders morgenochtend even om het op te lossen. PS: Volgens mij kun je -ipv los bestanden van oudere versie kopiëren- ook via de HACS Gui een oudere versie selecteren en installeren...

**Comment by Vircos01** [comment]
Allereerst dank voor deze prachtige integratie. Verder moet ik beamen dat ik tegen hetzelfde probleem aanloop. De betreffende entiteiten zijn blijkbaar opnieuw aangemaakt met de prefix "_2". Verder kan de entiteit "sensor.toon_p1_power_prod_cnt_high_2" niet meer worden toegevoegd aan het Energie dashboard binnen de teruglevering. Waar de low variant wel kan.

**Comment by cyberjunky** [comment]
@Vircos01 bedoel je dat een andere intergratie een issue heeft, zoja welke en wat is het issue dan? Heeft dat niet te maken met HA versie upgrate? 
Of doet toon_smartmeter het niet goed met bepaalde zonne opbrengst data?
Kun je in dat geval dan eventueel de json data posten?

Browse with a browser to an address like this http://ip:PORT/hdrv_zwave?action=getDevices.json and paste the output here...
Ip is address of your Toon, Port is 80 most of the time.

**Comment by cyberjunky** [comment]
Check ook of die _2 en _3 devices wel onder ontwikkelomgeving/statussen of onder apparaten/entities bestaan, ik heb gezien dat het energie dashboard ze soms zelf als history laat zien in die dropdowns, terwijl ze verder niet meer bestaan...

**Comment by Vircos01** [comment]
Zodra er zonnepanelen bij komen lijkt de toon_smartmeter integratie problemen te vertonen. Kan dat bijten?
Verder merk ik op dat de orginele entiteiten in *34 geen data meer loggen, maar op de laatst bekende stand blijven staan. De nieuwe entiteit loggen wel actuele data.

**Comment by Vircos01** [comment]
Dan mijn JSON:

{
  "dev_2": {
    "uuid": "d27f4b91-b9cb-4614-8eec-142f4c7940d7",
    "name": "HAE_METER_v3",
    "internalAddress": "2",
    "type": "HAE_METER_v3",
    "supportsCrc": "1",
    "ccList": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e",
    "supportedCC": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e",
    "nodeFlags": [],
    "IsConnected": "1",
    "HealthValue": "10",
    "DeviceName": "HAE_METER_v3",
    "CurrentSensorStatus": "UNKNOWN"
  },
  "dev_2.1": {
    "uuid": "1d99cd88-a609-42ab-9545-38badaf3af8c",
    "name": "HAE_METER_v3_1",
    "internalAddress": "2.1",
    "type": "gas",
    "supportsCrc": "0",
    "nodeFlags": [],
    "CurrentGasFlow": "479.00",
    "CurrentGasQuantity": "10918454.00",
    "DeviceName": "HAE_METER_v3_1"
  },
  "dev_2.2": {
    "uuid": "720ef24c-7df1-4503-a962-888c29f01567",
    "name": "HAE_METER_v3_2",
    "internalAddress": "2.2",
    "type": "elec",
    "supportsCrc": "0",
    "nodeFlags": [],
    "CurrentElectricityFlow": "NaN",
    "CurrentElectricityQuantity": "NaN",
    "DeviceName": "HAE_METER_v3_2"
  },
  "dev_2.3": {
    "uuid": "05b6e58e-9869-40c9-a764-bedadf2f5339",
    "name": "HAE_METER_v3_3",
    "internalAddress": "2.3",
    "type": "elec_solar",
    "supportsCrc": "0",
    "nodeFlags": [],
    "CurrentElectricityFlow": "NaN",
    "CurrentElectricityQuantity": "NaN",
    "DeviceName": "HAE_METER_v3_3"
  },
  "dev_2.4": {
    "uuid": "34eb0538-3243-4a24-8ebc-eb0fe9a0c393",
    "name": "HAE_METER_v3_4",
    "internalAddress": "2.4",
    "type": "elec_delivered_nt",
    "supportsCrc": "0",
    "nodeFlags": [],
    "CurrentElectricityFlow": "382.00",
    "CurrentElectricityQuantity": "17942896.00",
    "DeviceName": "HAE_METER_v3_4"
  },
  "dev_2.5": {
    "uuid": "c53cdadb-7724-4be8-85cf-640ec414296c",
    "name": "HAE_METER_v3_5",
    "internalAddress": "2.5",
    "type": "elec_received_nt",
    "supportsCrc": "0",
    "nodeFlags": [],
    "CurrentElectricityFlow": "0.00",
    "CurrentElectricityQuantity": "4960773.00",
    "DeviceName": "HAE_METER_v3_5"
  },
  "dev_2.6": {
    "uuid": "152cbabf-4c2e-48c6-bb96-2699e7066e38",
    "name": "HAE_METER_v3_6",
    "internalAddress": "2.6",
    "type": "elec_delivered_lt",
    "supportsCrc": "0",
    "nodeFlags": [],
    "CurrentElectricityFlow": "0.00",
    "CurrentElectricityQuantity": "14410183.00",
    "DeviceName": "HAE_METER_v3_6"
  },
  "dev_2.7": {
    "uuid": "90ee559d-910c-4f82-8362-47b9c156719d",
    "name": "HAE_METER_v3_7",
    "internalAddress": "2.7",
    "type": "elec_received_lt",
    "supportsCrc": "0",
    "nodeFlags": [],
    "CurrentElectricityFlow": "0.00",
    "CurrentElectricityQuantity": "2405326.00",
    "DeviceName": "HAE_METER_v3_7"
  },
  "dev_2.8": {
    "uuid": "5ab331fe-60ec-41e1-9d26-3c42186d68f5",
    "name": "HAE_METER_v3_8",
    "internalAddress": "2.8",
    "type": "heat",
    "supportsCrc": "0",
    "nodeFlags": [],
    "CurrentHeatQuantity": "NaN",
    "DeviceName": "HAE_METER_v3_8"
  },
  "dev_settings_device": {
    "uuid": "c8349114-83d9-4fee-bfe9-26a87a089336",
    "name": "settings_device",
    "internalAddress": "settings_device",
    "type": "settings_device"
  }
}

En overigens zie ik nu *37. Daarin blijft het probleem bestaan. Daarin worden weer nieuwe intiteiten met de _2 prefix aangemaakt.

**Comment by Vircos01** [comment]
En dan nog een specifiek voorbeeld:

![image](https://github.com/cyberjunky/home-assistant-toon_smartmeter/assets/57445752/488a239a-6768-46ec-b6e1-fb10a14c7cd0)

**Comment by cyberjunky** [comment]
@Vircos01 heb je de oude (stale) entities verwijderd en de intergratie opnieuw geinstalleerd na restart?
Zolang er oude devices bestaan (geen idee hoe die bij jou ontstaan zijn) zal ie dat blijven doen namelijk.
Zal zo kijken of die json file iets in de war gooit

**Comment by Vircos01** [comment]
Alle entiteiten verwijderd en integratie opnieuw geïnstalleerd. Na een herstart geen entiteiten meer gevonden met een prefix. Verder lijkt er wel weer data binnen te komen. Ik zal blijven monitoren hoe dit gaat verlopen. Blijft raar dat er na de update nieuwe entiteit zijn aangemaakt. Het energie dashboard laat nu ook geen fouten meer zien bij de zonnepanelen integraties. Voor nu lijken daarmee de problemen te zijn opgelost.

![image](https://github.com/cyberjunky/home-assistant-toon_smartmeter/assets/57445752/5daac6a9-1195-4919-8639-85ac1c3d0012)

**Comment by cyberjunky** [comment]
Ik zag ook geen rare dingen met je JSON, anders dan dat de solar waardes daar 'NaN' waren, er is in die code ook niks gewijzigd.
Ik heb ondertussen wel een manier bedacht om eea beter te laten werken (detectie en inlezen data) maar laat het voor nu zo.
Heb zo nog wel een kleine update (code opschoon)
Excuses voor ongemakt maar moest ineens veel van mijn integraties updaten voordat HA 2024 uit kwam, en zat krap in de tijd.

**Comment by Vircos01** [comment]
NaN kan wel kloppen. Die lees ik niet uit via Toon, maar via de eigen integraties van de betreffende omvormers.
Verder alle begrip hoor. Super werk dat je levert.

**Comment by Jopandrik** [comment]
Hoi Ron,

Ik heb het probleem nog steeds niet op weten te lossen!
By alle sensors wordt de waarde **Unknown** aangegeven.
Hieronder een voorbeeld:
             
![image](https://github.com/cyberjunky/home-assistant-toon_smartmeter/assets/112260178/02e284fa-722a-42f6-8cc4-6c95c0965146)

Zoals je zelf kunt zien wordt deze waarde bij alle smartmeter entiteiten aangegeven:
![image](https://github.com/cyberjunky/home-assistant-toon_smartmeter/assets/112260178/a421becf-2ea6-4ef2-a074-b5d5fecaacb6)

Ik heb de indruk dat de smartmeter integratie in een loop is terecht gekomen.
Ik heb geen Poweplugs op mijn Toon2 aangesloten!

Ik de log zie ik elke 10 seconden het volgende voorbijkomen:

2024-01-05 22:53:41.091 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Device: gasusedcnt State: None PowerPlug: 
2024-01-05 22:53:41.091 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Device: elecusageflowpulse State: None PowerPlug: 
2024-01-05 22:53:41.092 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Device: elecusageflowlow State: None PowerPlug: 
2024-01-05 22:53:41.092 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Device: elecusageflowhigh State: None PowerPlug: 
2024-01-05 22:53:41.092 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Device: elecprodflowlow State: None PowerPlug: 
2024-01-05 22:53:41.093 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Device: elecprodflowhigh State: None PowerPlug: 
2024-01-05 22:53:41.093 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Device: elecusagecntpulse State: None PowerPlug: 
2024-01-05 22:53:41.093 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Device: elecusagecntlow State: None PowerPlug: 
2024-01-05 22:53:41.094 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Device: elecusagecnthigh State: None PowerPlug: 
2024-01-05 22:53:41.094 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Device: elecprodcntlow State: None PowerPlug: 
2024-01-05 22:53:41.094 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Device: elecprodcnthigh State: None PowerPlug: 
2024-01-05 22:53:41.123 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Data received from Toon: {'dev_settings_device': {'uuid': 'd4462fff-b5f4-4bb0-b76b-74d12adc0e3f', 'name': 'settings_device', 'internalAddress': 'settings_device', 'type': 'settings_device'}}
2024-01-05 22:53:41.123 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Device: gasused State: None PowerPlug: 

Ik heb de complete log als bijlage toegevoegd

Met vriendelijke groet, Jopandrik
[home-assistant.log](https://github.com/cyberjunky/home-assistant-toon_smartmeter/files/13847103/home-assistant.log)

**Comment by Jopandrik** [comment]
Vergeten te melden dat ik gebruik maakvan versie 1.0.38 en HA Core 2024.1.1

**Comment by Jopandrik** [comment]
Hoi Ron,

Er lijkt iets met mijn toon2 aan de hand te zijn!
Dat had je waarschijnlijk al gezien :-)

Dit is wat ik terug krijg:

curl http://192.168.2.248/hdrv_zwave?action=getDevices.json
{"dev_settings_device": {"uuid": "d4462fff-b5f4-4bb0-b76b-74d12adc0e3f", "name": "settings_device", "internalAddress": "settings_device", "type": "settings_device"}}

Gisteren kreeg ik nog een nette JSON file te zien!!!!

Weet jij toevallig wat de oorzaak zou kunnen zijn? 

Groet, Jopandrik

**Comment by Jopandrik** [comment]
Ik heb de fout kunnen herstellen :-)
Mijn Toon2 was niet meer verbonden met de meet module!

**Comment by Jopandrik** [comment]
Mijn JSON file:

{
	"dev_settings_device": {
		"uuid": "d4462fff-b5f4-4bb0-b76b-74d12adc0e3f",
		"name": "settings_device",
		"internalAddress": "settings_device",
		"type": "settings_device"
	},
	"dev_5": {
		"uuid": "4ba31320-14ec-45f1-93b4-d651c752e91b",
		"name": "HAE_METER_v3",
		"internalAddress": "5",
		"type": "HAE_METER_v3",
		"supportsCrc": "1",
		"ccList": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e",
		"supportedCC": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e",
		"nodeFlags": [],
		"IsConnected": "1",
		"HealthValue": "1",
		"DeviceName": "HAE_METER_v3",
		"CurrentSensorStatus": "UNKNOWN"
	},
	"dev_5.1": {
		"uuid": "ad7c1d2a-ca47-440a-8cf6-b617207feb34",
		"name": "HAE_METER_v3_1",
		"internalAddress": "5.1",
		"type": "HAE_METER_v3_1",
		"supportsCrc": "0",
		"ccList": "5e 59 85 8e 3c 3d 3e",
		"supportedCC": "5e 59 85 8e 3c 3d 3e",
		"nodeFlags": [],
		"CurrentSensorStatus": "OPERATIONAL",
		"CurrentGasFlow": "0.00",
		"CurrentGasQuantity": "7683003.00",
		"DeviceName": ""
	},
	"dev_5.2": {
		"uuid": "b6b55a7b-7ec3-4309-957f-a751678d7067",
		"name": "HAE_METER_v3_2",
		"internalAddress": "5.2",
		"type": "HAE_METER_v3_2",
		"supportsCrc": "0",
		"ccList": "5e 59 85 8e 3c 3d 3e",
		"supportedCC": "5e 59 85 8e 3c 3d 3e",
		"nodeFlags": [],
		"CurrentSensorStatus": "UNKNOWN",
		"DeviceName": "",
		"CurrentElectricityFlow": "NaN",
		"CurrentElectricityQuantity": "NaN"
	},
	"dev_5.3": {
		"uuid": "2f349615-0755-4bd5-9620-2cb041600397",
		"name": "HAE_METER_v3_3",
		"internalAddress": "5.3",
		"type": "HAE_METER_v3_3",
		"supportsCrc": "0",
		"ccList": "5e 59 85 8e 3c 3d 3e",
		"supportedCC": "5e 59 85 8e 3c 3d 3e",
		"nodeFlags": [],
		"CurrentSensorStatus": "UNKNOWN",
		"DeviceName": "",
		"CurrentElectricityFlow": "NaN",
		"CurrentElectricityQuantity": "NaN"
	},
	"dev_5.4": {
		"uuid": "d7d986f1-ab35-4e43-a2a4-1014a0df3f35",
		"name": "HAE_METER_v3_4",
		"internalAddress": "5.4",
		"type": "HAE_METER_v3_4",
		"supportsCrc": "0",
		"ccList": "5e 59 85 8e 3c 3d 3e",
		"supportedCC": "5e 59 85 8e 3c 3d 3e",
		"nodeFlags": [],
		"CurrentSensorStatus": "OPERATIONAL",
		"DeviceName": "",
		"CurrentElectricityFlow": "0.00",
		"CurrentElectricityQuantity": "6328971.00"
	},
	"dev_5.5": {
		"uuid": "f3e92380-7446-4d4e-a4cf-84103644515a",
		"name": "HAE_METER_v3_5",
		"internalAddress": "5.5",
		"type": "HAE_METER_v3_5",
		"supportsCrc": "0",
		"ccList": "5e 59 85 8e 3c 3d 3e",
		"supportedCC": "5e 59 85 8e 3c 3d 3e",
		"nodeFlags": [],
		"CurrentSensorStatus": "UNKNOWN",
		"DeviceName": "",
		"CurrentElectricityFlow": "0.00",
		"CurrentElectricityQuantity": "7785197.00"
	},
	"dev_5.6": {
		"uuid": "7197f75f-dd0f-44f6-84fc-13ffd4ce9574",
		"name": "HAE_METER_v3_6",
		"internalAddress": "5.6",
		"type": "HAE_METER_v3_6",
		"supportsCrc": "0",
		"ccList": "5e 59 85 8e 3c 3d 3e",
		"supportedCC": "5e 59 85 8e 3c 3d 3e",
		"nodeFlags": [],
		"CurrentSensorStatus": "UNKNOWN",
		"DeviceName": "",
		"CurrentElectricityFlow": "1343.00",
		"CurrentElectricityQuantity": "25426938.00"
	},
	"dev_5.7": {
		"uuid": "ac24de50-bfd2-4545-914b-32a04de87cff",
		"name": "HAE_METER_v3_7",
		"internalAddress": "5.7",
		"type": "HAE_METER_v3_7",
		"supportsCrc": "0",
		"ccList": "5e 59 85 8e 3c 3d 3e",
		"supportedCC": "5e 59 85 8e 3c 3d 3e",
		"nodeFlags": [],
		"CurrentSensorStatus": "UNKNOWN",
		"DeviceName": "",
		"CurrentElectricityFlow": "0.00",
		"CurrentElectricityQuantity": "3387192.00"
	},
	"dev_5.8": {
		"uuid": "ff121693-510c-4dd5-af37-24e4fa4d5647",
		"name": "HAE_METER_v3_8",
		"internalAddress": "5.8",
		"type": "HAE_METER_v3_8",
		"supportsCrc": "0",
		"ccList": "5e 59 85 8e 3c 3d 3e",
		"supportedCC": "5e 59 85 8e 3c 3d 3e",
		"nodeFlags": [],
		"CurrentSensorStatus": "UNKNOWN",
		"DeviceName": "",
		"CurrentHeatQuantity": "NaN",
		"CurrentHeatFlow": "NaN"
	}
}

**Comment by Jopandrik** [comment]
Hoi Ron,

Bedankt voor de prima ondersteuning.
Vervelend dat bleek dat vrijwel tegelijkertijd mijn toon plotsklaps geen
verbinding  meer had met de metermodule. Dat is nog niet eerder gebeurd.
Murphy zal over mijn schouder wel meegekeken hebben :-)
Heb je nog plannen om de temperatuursensor van de Toon 2 uit te lezen en
beschikbaar te stellen in HA?

**Comment by cyberjunky** [comment]
@Jopandrik Geen probleem en graag gedaan!
Bedoel je de extra sensoren in de Toon2? Ik heb er zelf een maar ooit dit gedocumenteerd op de README pagina van de toon_climate intergratie, resource moet uiteraard het ip adres van jou Toon2 bevatten. Ik ga maar eens kijken naar een Toon2 op marktplaats denk, mijn oude Toon1 is niet meer zo stabiel. ;-)

```sensor:
  - platform: rest
    name: Toon2 AirSensors
    json_attributes:
      - humidity
      - tvoc
      - eco2
    value_template: '{{ value_json["temperature"] }}'
    device_class: temperature
    unit_of_measurement: "°C"
    resource: http://192.168.2.106/tsc/sensors

template:
  - sensor:
    - name: "Toon2 Humidity"
      state: '{{ states.sensor.toon2_airsensors.attributes["humidity"] }}'
      device_class: humidity
      state_class: measurement
    - name: "Toon2 TVOC"
      state: '{{ states.sensor.toon2_airsensors.attributes["tvoc"] }}'
      device_class: volatile_organic_compounds
      state_class: measurement
    - name: "Toon2 eCO2"
      state: '{{ states.sensor.toon2_airsensors.attributes["eco2"] }}'
      device_class: carbon_dioxide
      state_class: measurement```

**Comment by Jopandrik** [comment]
@Ron: ja die bedoel ik.

curl http://192.168.2.248/tsc/sensors: {"temperature":21.5,
"humidity":46.0, "tvoc":1123, "eco2":2192, "intensity":0}
Dit is de JSON:

{
"temperature": 21.5,
"humidity": 46.0,
"tvoc": 1123,
"eco2": 2192,
"intensity": 0
}

Op Marktplaats kun je een Toon2 scoren vanaf 40 € en hoger. Ik heb hem
destijds voor € aangeschaft.

Met vriendelijke groet, Jopandrik

**Comment by cyberjunky** [comment]
Die kun je mee de 'rest' config uitlezen welke ik hierboven gepost heb, daar is geen integratie verder bij nodig.

**Comment by johanvanderkuijl** [comment]
Na een recente update via HACS naar 1.0.38 merkte ik dat ik mijn gasmeterstand niet meer werd geupdate. Er zijn nieuwe entiteiten aangemaakt, met suffix _2. Dit probleem heb ik wel vaker gezien bij andere integraties, en is niet specifiek Toon gerelateerd.
De nieuwe entiteiten loggen wel de data, de oude niet, en die blijven dus 'stale' op je dashboard staan.
Een eenvoudige oplossing is dan:

1. verwijder de originele entiteiten die geen _2 suffix hebben.
2. hernoem de entiteiten die wel een _2 suffix hebben naar de originele naam zonder _2 suffix

bijvoorbeeld:
`toon_gas_used_cnt  <-- verwijder deze
toon_gas_used_cnt_2  <-- hernoem deze naar toon_gas_used_cnt`

Nu werkt alles weer naar behoren.
