### ISSUE TITLE
Updates renamen sensoren, history weg?

### ISSUE THREAD

**Issue by mensoh** [cyberjunky/home-assistant-toon_smartmeter#80]
Hoi, 

Er zijn de afgelopen weken meerdere updates geweest die de sensoren renamed lijken te hebben. Lang verhaal kort, paar keer de sensoren opnieuw moeten invoeren in het energy dashboard waar ik geschiedenis van 5 jaar terug in had en momenteel alleen de afgelopen week nog in kan zien. Enige tips over hoe dit te fixen zijn welkom!

Thanks

**Comment by cyberjunky** [comment]
Ja ik moest eea flink omgooien door verandering in HA 2024, al zou dat eigenlijk niet moeten leiden naar andere benaming (staat er _2 achter de naam?)

Wellicht helpt dit stappenplan je ander gemaakte ticket je:


> make a full backup
> disable smartmeter integration (comment config)
> restart
> remove device sensor.toon_power_use and sensor.toon_power_use_cnt
> rename sensor.toon_p1_power_use to sensor.toon_power_use (using clogwheel in device entitiy-id)
> same for _cnt device
> enable integration in code
> restart
> Thanks. Those steps really helped. I ended up doing:

or 

> make a full backup
> disable smartmeter integration (comment config)
> restart
> removed all entities related to toon_smartmeter
> enable integration in code
> restart

Tip, maak altijd backups

**Comment by Jopandrik** [comment]
Ik heb hetzelfde probleem. 

Moet ik voor het uitvoeren van het bovenstaande eerst al een installatie van 1.0.36 hebben uitgevoerd?
Moeten er nog extra stappen uitgevoeren worden wannner je een dubbeltarief slimme meter en zonnepanelen hebt?
Op welke plek in HA moet ik wezen om stap 4 (remove device) en stap 5 (rename sensor) uit te voeren?

**Comment by cyberjunky** [comment]
> Ik heb hetzelfde probleem.
> 
> Moet ik voor het uitvoeren van het bovenstaande eerst al een installatie van 1.0.36 hebben uitgevoerd? Moeten er nog extra stappen uitgevoerd worden wanneer je een dubbeltarief slimme meter en zonnepanelen hebt? Op welke plek in HA moet ik wezen om stap 4 (remove device) en stap 5 (rename sensor) uit te voeren?

Het eerste lijstje met stappen was wat ik uit het hoofd had voorgesteld, het tweede lijstje was hoe een gebruiker het hand uitgevoerd., in het kort komt het er op neer dat de oude id's die niet actief zijn weg moeten, dan een herstart of herinstall met herstart en dan heb je de originele devices weer, wel eerst backup maken dus
