### ISSUE TITLE
After update to new version sensors are renamed/duplicates

### ISSUE THREAD

**Issue by Dessie69** [cyberjunky/home-assistant-toon_smartmeter#81]
When upgrading from version 1.31 to 1.38 my sensors are now duplicated

for example:
toon_p1_power_use_cnt_high => toon_p1_power_use_cnt_high_2
toon_p1_power_use_cnt_low => toon_p1_power_use_cnt_low_2

This means that my history is now gone because the new sensors are reporting the values and not the old ones.
I read that in version 1.32 the sensors were renamed, perhaps that is the reason.

**Comment by cyberjunky** [comment]
Yes, unfortunately a result of fixing deprecated device code for 2024 home assistant, see here for fix: https://github.com/cyberjunky/home-assistant-toon_smartmeter/issues/78#issuecomment-1873514888

**Comment by Dessie69** [comment]
I fixed it by stopping HA and making a backup of the core.entity_registry
Then I remove the old entities and renamed the new entities with the _2 to the old name. 
After restarting HA the new entities are now reporting under the old name so the history is back (as far as I can see)
