### ISSUE TITLE
After update all values are unknown

### ISSUE THREAD

**Issue by JackKlaasing** [cyberjunky/home-assistant-toon_smartmeter#82]
After update all my values were duplicated by "*_2" but I got it fixed.
But after a day or two now all values are unknown and won't update anymore.

Toon Climate works good
Toon Smartmeter doesn't.

Setup:

`# Example groups.yaml entry

Smart Meter:
  - sensor.toon_gas_used_last_hour
  - sensor.toon_gas_used_cnt
  - sensor.toon_power_use_cnt
  - sensor.toon_power_use
  - sensor.toon_p1_power_prod_low
  - sensor.toon_p1_power_prod_high
  - sensor.toon_p1_power_prod_cnt_low
  - sensor.toon_p1_power_prod_cnt_high
  - sensor.toon_p1_power_use_cnt_pulse
  - sensor.toon_p1_power_use_cnt_low
  - sensor.toon_p1_power_use_cnt_high
  - sensor.toon_p1_power_use_low
  - sensor.toon_p1_power_use_high
  - sensor.toon_p1_power_solar
  - sensor.toon_p1_power_solar_cnt
  - sensor.toon_p1_heat
  - sensor.toon_p1_waterflow
  - sensor.toon_p1_waterquantity`

configuration.yaml
`sensor:
  - platform: toon_smartmeter
    host: 192.168.178.79
    port: 80
    scan_interval: 10
    resources:
      - gasused
      - gasusedcnt
      - elecusageflowpulse
      - elecusagecntpulse
      - elecusageflowlow
      - elecusagecntlow
      - elecusageflowhigh
      - elecusagecnthigh
      - elecprodflowlow
      - elecprodcntlow
      - elecprodflowhigh
      - elecprodcnthigh
      - elecsolar
      - elecsolarcnt
      - heat
      - waterflow
      - waterquantity

logger:
  default: info
  logs:
    custom_components.toon_smartmeter: debug`

**Comment by cyberjunky** [comment]
I guess there is an issue with access to your toon, check logs. Maybe ip address changed?

**Comment by cyberjunky** [comment]
Thanks, the JSON doesn't seem to contain energy usage data, could it be that the Toon lost connection with the smartmeter module? Does the Toon shows the realtime smartmeter data still?

**Comment by JackKlaasing** [comment]
Yes that is still working correctly.

**Comment by JackKlaasing** [comment]
I use a P1 splitter at the moment but it always worked together. I could try to only use 1.

**Comment by cyberjunky** [comment]
Until there is no data in the JSON the integration will not work, so cause is outside home-assistant.

**Comment by MagieMalone** [comment]
I have the same issue. the data IS on the toon, I can access the internal graphs there, but not pulled by the integration.  Also not on the JSON:

```2024-02-09 19:02:34.457 DEBUG (MainThread) [custom_components.toon_smartmeter.sensor] Data received from Toon: {'dev_2': {'uuid': '88322d9f-0763-4714-8e63-7ffb1c87088d', 'name': 'HAE_METER_v3', 'internalAddress': '2', 'type': 'HAE_METER_v3', 'supportsCrc': '1', 'ccList': '5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e', 'supportedCC': '5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e', 'nodeFlags': [], 'IsConnected': '1', 'DeviceName': 'HAE_METER_v3', 'HealthValue': '10', 'CurrentSensorStatus': 'UNKNOWN'}, 'dev_2.1': {'uuid': '11097cc6-c5f1-43ed-8a9a-c29a81aa2007', 'name': 'HAE_METER_v3_1', 'internalAddress': '2.1', 'type': 'gas', 'supportsCrc': '0', 'ccList': '5e 59 85 8e 3c 3d 3e', 'supportedCC': '5e 59 85 8e 3c 3d 3e', 'nodeFlags': [], 'CurrentGasFlow': '40.00', 'CurrentGasQuantity': '5246560.00', 'DeviceName': 'HAE_METER_v3_1', 'CurrentSensorStatus': 'OPERATIONAL'}, 'dev_2.2': {'uuid': '07aeef14-616b-4470-b009-430c59ba0b9a', 'name': 'HAE_METER_v3_2', 'internalAddress': '2.2', 'type': 'elec', 'supportsCrc': '0', 'ccList': '5e 59 85 8e 3c 3d 3e', 'supportedCC': '5e 59 85 8e 3c 3d 3e', 'nodeFlags': [], 'CurrentElectricityFlow': 'NaN', 'CurrentElectricityQuantity': 'NaN', 'DeviceName': 'HAE_METER_v3_2', 'CurrentSensorStatus': 'UNKNOWN'}, 'dev_2.3': {'uuid': '7da5a6f7-693e-4287-a229-1bbf416ccd39', 'name': 'HAE_METER_v3_3', 'internalAddress': '2.3', 'type': 'elec_solar', 'supportsCrc': '0', 'ccList': '5e 59 85 8e 3c 3d 3e', 'supportedCC': '5e 59 85 8e 3c 3d 3e', 'nodeFlags': [], 'CurrentElectricityFlow': 'NaN', 'CurrentElectricityQuantity': 'NaN', 'DeviceName': 'HAE_METER_v3_3', 'CurrentSensorStatus': 'UNKNOWN'}, 'dev_2.4': {'uuid': 'c0c7a380-26b2-484e-b566-66c952aa498c', 'name': 'HAE_METER_v3_4', 'internalAddress': '2.4', 'type': 'elec_delivered_nt', 'supportsCrc': '0', 'ccList': '5e 59 85 8e 3c 3d 3e', 'supportedCC': '5e 59 85 8e 3c 3d 3e', 'nodeFlags': [], 'CurrentElectricityFlow': '1438.00', 'CurrentElectricityQuantity': '9594543.00', 'DeviceName': 'HAE_METER_v3_4', 'CurrentSensorStatus': 'OPERATIONAL'}, 'dev_2.5': {'uuid': '1d23dccf-34b2-47e9-bfd2-74d073a7e0a7', 'name': 'HAE_METER_v3_5', 'internalAddress': '2.5', 'type': 'elec_received_nt', 'supportsCrc': '0', 'ccList': '5e 59 85 8e 3c 3d 3e', 'supportedCC': '5e 59 85 8e 3c 3d 3e', 'nodeFlags': [], 'CurrentElectricityFlow': '0.00', 'CurrentElectricityQuantity': '0.00', 'DeviceName': 'HAE_METER_v3_5', 'CurrentSensorStatus': 'UNKNOWN'}, 'dev_2.6': {'uuid': 'c310023c-6882-4619-a4e9-a3475cea2fc0', 'name': 'HAE_METER_v3_6', 'internalAddress': '2.6', 'type': 'elec_delivered_lt', 'supportsCrc': '0', 'ccList': '5e 59 85 8e 3c 3d 3e', 'supportedCC': '5e 59 85 8e 3c 3d 3e', 'nodeFlags': [], 'CurrentElectricityFlow': '0.00', 'CurrentElectricityQuantity': '9477192.00', 'DeviceName': 'HAE_METER_v3_6', 'CurrentSensorStatus': 'UNKNOWN'}, 'dev_2.7': {'uuid': '5e595218-6d7a-4f11-acef-a8b582d4fe4e', 'name': 'HAE_METER_v3_7', 'internalAddress': '2.7', 'type': 'elec_received_lt', 'supportsCrc': '0', 'ccList': '5e 59 85 8e 3c 3d 3e', 'supportedCC': '5e 59 85 8e 3c 3d 3e', 'nodeFlags': [], 'CurrentElectricityFlow': '0.00', 'CurrentElectricityQuantity': '0.00', 'DeviceName': 'HAE_METER_v3_7', 'CurrentSensorStatus': 'UNKNOWN'}, 'dev_2.8': {'uuid': '19f8d08e-e644-470b-b8e4-613d50f48c33', 'name': 'HAE_METER_v3_8', 'internalAddress': '2.8', 'type': 'heat', 'supportsCrc': '0', 'ccList': '5e 59 85 8e 3c 3d 3e', 'supportedCC': '5e 59 85 8e 3c 3d 3e', 'nodeFlags': [], 'CurrentHeatQuantity': 'NaN', 'DeviceName': 'HAE_METER_v3_8', 'CurrentSensorStatus': 'UNKNOWN', 'CurrentHeatFlow': 'NaN'}, 'dev_settings_device': {'uuid': 'f5bf5c01-7edd-4040-af16-d1b08b5cccf8', 'name': 'settings_device', 'internalAddress': 'settings_device', 'type': 'settings_device'}}```

**Comment by JackKlaasing** [comment]
I didn't fix it yet, please let me know if you want the fix!

**Comment by cyberjunky** [comment]
@JackKlaasing check for duplicate sensors like toon_gas_used_cnt_2 these will probably hold the current values.
If so, read here for possible fixes:

https://github.com/cyberjunky/home-assistant-toon_smartmeter/issues/78#issuecomment-1873514888

**Comment by JackKlaasing** [comment]
> @JackKlaasing check for duplicate sensors like toon_gas_used_cnt_2 these will probably hold the current values. If so, read here for possible fixes:
> 
> [#78 (comment)](https://github.com/cyberjunky/home-assistant-toon_smartmeter/issues/78#issuecomment-1873514888)

I don't have the duplicate values anymore.
In the past I had, after the last update.

Then I had to fix it and it was working again but after a day or two it stopped again.

**Comment by cyberjunky** [comment]
Are you sure the ip address/port of the toon still matches the config?
This integration is very simple, there is not much to break...

**Comment by cyberjunky** [comment]
Is the url listed in the log file (if debug enable) correct?

**Comment by JackKlaasing** [comment]
> Is the url listed in the log file (if debug enable) correct?

Yes it's correct. I use the same IP for the thermostat and that one is working correctly.

**Comment by cyberjunky** [comment]
Can you post the debug log output for this integration, from startup to first poll(s)?

**Comment by MagieMalone** [comment]
> @JackKlaasing check for duplicate sensors like toon_gas_used_cnt_2 these will probably hold the current values. If so, read here for possible fixes:
> 
> [#78 (comment)](https://github.com/cyberjunky/home-assistant-toon_smartmeter/issues/78#issuecomment-1873514888)

for me this worked. I'm annoyed at myself for not noticing the duplicate sensors.

**Comment by cyberjunky** [comment]
It had to do with some changes I needed to make to be compatible with current HA versions
