### ISSUE TITLE
Sensors become unavailable after restart of HA

### ISSUE THREAD

**Issue by Flashlab2** [cyberjunky/home-assistant-toon_smartmeter#83]
Hi all,

I have been using this nice integration for over a year without issue but since a few weeks I have a problem.

After a restart of HA sometimes the Toon Smart Meter sensors have the status unavailable in HA and don't recover. This results in my energyboard missing hours/days of information until I fix it.

The fix is removing one of the unavailable sensors and restarting. Most of the time this fixes it but it's not a 100% fix. Sometimes I have to multiple times.

Any ideas on why this is happening?

**Comment by cyberjunky** [comment]
@sprangnl2 The ones you miss are called '...cost' sensors, which are not part of the smartmeter integraton, I guess you calculate those using a template sensor, maybe there is an issue? Also you cannot have Power Use Cnt and P1 sensors at the same time, so the last one seems as misconfiguration (you need to not query that one I guess) If the solar ones did work before, can you enable debug and sent the logfile part?

**Comment by cyberjunky** [comment]
> Hi all,
> 
> I have been using this nice integration for over a year without issue but since a few weeks I have a problem.
> 
> After a restart of HA sometimes the Toon Smart Meter sensors have the status unavailable in HA and don't recover. This results in my energyboard missing hours/days of information until I fix it.
> 
> The fix is removing one of the unavailable sensors and restarting. Most of the time this fixes it but it's not a 100% fix. Sometimes I have to multiple times.
> 
> Any ideas on why this is happening?

If you upgraded this integration lately, due to some needed architectural changes I needed to make to have it work on newer HA, you needed to throw away the old sensors since new ones where created, if you didn't upgrade, you maybe need to do this... else enable debug and sent the log and I will have a look...

**Comment by Flashlab2** [comment]
For me the problem seems to be fixed. I did indeed update the old sensors already.

**Comment by sprangnl2** [comment]
oke i will check my configuration and collect the log files

**Comment by cyberjunky** [comment]
Closing because stale ticket
