### ISSUE TITLE
Energy dashboard setup

### ISSUE THREAD

**Issue by xaetacore** [cyberjunky/home-assistant-toon_smartmeter#85]
I see in ur readme that you provided a screenshot of how you could set it up, however it looks like its not working for me

is there any way you could show me how to set it up properly?

**Comment by cyberjunky** [comment]
Just make sure you have the counters working (cnt) and add them to the energy dashboard, that is all..

![image](https://github.com/user-attachments/assets/d12deba3-1b26-4d6e-8ebf-f2872afbef8e)

What exactly do you run into?

**Comment by xaetacore** [comment]
well some of the values like

Toon p1 power cnt don't exist

i only have high and low for example

**Comment by cyberjunky** [comment]
@xaetacore do you have a P1 smartmeter, and did you include those cnt values also in the config?
```
    resources:
      - gasused
      - gasusedcnt
      - elecusageflowpulse
      - elecusagecntpulse
      - elecusageflowlow
      - elecusagecntlow
      - elecusageflowhigh
      - elecusagecnthigh
      - elecprodflowlow
      - elecprodcntlow
      - elecprodflowhigh
      - elecprodcnthigh

**Comment by xaetacore** [comment]
Yea i do and i have everything in there

mine looks like this 
![image](https://github.com/user-attachments/assets/55e702de-8396-45d3-9cdb-9da713e62fe5)

**Comment by cyberjunky** [comment]
@xaetacore Yes that looks fine, so you found the devices now? It takes time to show some results.

**Comment by cyberjunky** [comment]
No problem!
