### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by ahforster** [cyberjunky/home-assistant-toon_smartmeter#87]
I added the smartmeter. Edited the configuration Yaml and the groups.yaml.
The entities are visible, but show no data. I have another P1 meter running from Homewizzard, but due to power failures lately i want to switch to your solution. 
<img width="483" alt="Scherm­afbeelding 2024-08-06 om 14 43 16" src="https://github.com/user-attachments/assets/eed5ff44-8a22-47bf-a663-c76f211c3b7f">
<img width="465" alt="Scherm­afbeelding 2024-08-06 om 14 43 40" src="https://github.com/user-attachments/assets/2d0e0d59-50ef-40a9-b9b5-292e9d91f18b">
<img width="583" alt="Scherm­afbeelding 2024-08-06 om 14 55 29" src="https://github.com/user-attachments/assets/49a69bd9-8700-4a93-bb79-36d3c197ebca">

**Comment by ahforster** [comment]
found it!. The "meetmodule" was not connected.....
My mistake..

**Comment by cyberjunky** [comment]
No problem, glad it worked!
